AllCops:
  Include:
    - '**/config.ru'
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'db/**/*'
    - 'config/environments/*'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false

#48Files / 11Offenses
