
Destination.create(name: 'Maldives')
Destination.create(name: 'Male')
Destination.create(name: 'Mauritius')
Destination.create(name: 'Canaries')
Destination.create(name: 'Fuerteventura')
Destination.create(name: 'Antigua')
Destination.create(name: 'Caleta De Fuste')
Destination.create(name: 'Corralejo')
Destination.create(name: 'Costa Calma')
Destination.create(name: 'Playa De Jandia')
Destination.create(name: 'Gran Canaria')
Destination.create(name: 'Arguineguin')
Destination.create(name: 'Las Palmas')
Destination.create(name: 'Maspalomas')
Destination.create(name: 'Meloneras')
Destination.create(name: 'Playa Del Ingles')
Destination.create(name: 'Puerto Rico')
Destination.create(name: 'San Agustin')
Destination.create(name: 'Sonnenland')
Destination.create(name: 'Lanzarote')
Destination.create(name: 'Costa Calero')
Destination.create(name: 'Costa Teguise')
Destination.create(name: 'Matagorda')
Destination.create(name: 'Playa Blanca')
Destination.create(name: 'Puerto Del Carmen')
Destination.create(name: 'Playa De Los Pocillos')
Destination.create(name: 'Tenerife')
Destination.create(name: 'Playa De Las Americas')
Destination.create(name: 'Costa Adeje')
Destination.create(name: 'Costa Del Silencio')
Destination.create(name: 'El Medano')
Destination.create(name: 'Golf Del Sur')
Destination.create(name: 'Las Caletillas')
Destination.create(name: 'Los Cristianos')
Destination.create(name: 'Playa De La Arena')
Destination.create(name: 'Playa Paraiso')
Destination.create(name: 'Puerto De La Cruz')
Destination.create(name: 'Puerto Santiago')
Destination.create(name: 'Santa Ursula')
Destination.create(name: 'Caribbean')
Destination.create(name: 'Bahamas')
Destination.create(name: 'Cayman Islands')
Destination.create(name: 'Bermuda')
Destination.create(name: 'Barbados')
Destination.create(name: 'Antigua and Barbuda')
Destination.create(name: 'Cuba')
Destination.create(name: 'Jamaica')
Destination.create(name: 'Grenada')
Destination.create(name: 'Trinidad and Tobago')
Destination.create(name: 'St Lucia')
