maldives = Destination.find_by_name('Maldives')
male = Destination.find_by_name('Male')
mauritius = Destination.find_by_name('Mauritius')
canaries = Destination.find_by_name('Canaries')
fuerteventura = Destination.find_by_name('Fuerteventura')
antigua = Destination.find_by_name('Antigua')
caleta_de_fuste = Destination.find_by_name('Caleta De Fuste')
corralejo = Destination.find_by_name('Corralejo')
costa_calma = Destination.find_by_name('Costa Calma')
playa_de_jandia = Destination.find_by_name('Playa De Jandia')
gran_canaria = Destination.find_by_name('Gran Canaria')
arguineguin = Destination.find_by_name('Arguineguin')
las_palmas = Destination.find_by_name('Las Palmas')
maspalomas = Destination.find_by_name('Maspalomas')
meloneras = Destination.find_by_name('Meloneras')
playa_del_ingles = Destination.find_by_name('Playa Del Ingles')
puerto_rico = Destination.find_by_name('Puerto Rico')
san_agustin = Destination.find_by_name('San Agustin')
sonnenland = Destination.find_by_name('Sonnenland')
lanzarote = Destination.find_by_name('Lanzarote')
costa_calero = Destination.find_by_name('Costa Calero')
costa_teguise = Destination.find_by_name('Costa Teguise')
matagorda = Destination.find_by_name('Matagorda')
playa_blanca = Destination.find_by_name('Playa Blanca')
puerto_del_carmen = Destination.find_by_name('Puerto Del Carmen')
playa_de_los_pocillos = Destination.find_by_name('Playa De Los Pocillos')
tenerife = Destination.find_by_name('Tenerife')
playa_de_las_americas = Destination.find_by_name('Playa De Las Americas')
costa_adeje = Destination.find_by_name('Costa Adeje')
costa_del_silencio = Destination.find_by_name('Costa Del Silencio')
el_medano = Destination.find_by_name('El Medano')
golf_del_sur = Destination.find_by_name('Golf Del Sur')
las_caletillas = Destination.find_by_name('Las Caletillas')
los_cristianos = Destination.find_by_name('Los Cristianos')
playa_de_la_arena = Destination.find_by_name('Playa De La Arena')
playa_paraiso = Destination.find_by_name('Playa Paraiso')
puerto_de_la_cruz = Destination.find_by_name('Puerto De La Cruz')
puerto_santiago = Destination.find_by_name('Puerto Santiago')
santa_ursula = Destination.find_by_name('Santa Ursula')
caribbean = Destination.find_by_name('Caribbean')
bahamas = Destination.find_by_name('Bahamas')
cayman_islands = Destination.find_by_name('Cayman Islands')
bermuda = Destination.find_by_name('Bermuda')
barbados = Destination.find_by_name('Barbados')
antigua_and_barbuda = Destination.find_by_name('Antigua and Barbuda')
cuba = Destination.find_by_name('Cuba')
jamaica = Destination.find_by_name('Jamaica')
grenada = Destination.find_by_name('Grenada')
trinidad_and_tobago = Destination.find_by_name('Trinidad and Tobago')
st_lucia = Destination.find_by_name('St Lucia')

Hotel.create(name: 'Siesta I', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Servatur Waikiki', destinations_id: el_medano.id)
Hotel.create(name: 'Grifone', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Blue Sea Costa Teguise Gardens', destinations_id: las_caletillas.id)
Hotel.create(name: 'Gounod', destinations_id: los_cristianos.id)
Hotel.create(name: 'Sultan Bey', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Kyriad Nice Centre Port', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Palia Las Palomas', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Playalinda', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Marina Bayview - Adult Only', destinations_id: santa_ursula.id)
Hotel.create(name: 'Columbus Aparthotel', destinations_id: caribbean.id)
Hotel.create(name: 'Zoraida Garden', destinations_id: bahamas.id)
Hotel.create(name: 'Villas Santa Ana', destinations_id: cayman_islands.id)
Hotel.create(name: 'SBH Fuerteventura Playa', destinations_id: bermuda.id)
Hotel.create(name: 'Presidente', destinations_id: barbados.id)
Hotel.create(name: 'Palazzo Alabardieri', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Teguisol', destinations_id: cuba.id)
Hotel.create(name: 'Panorama', destinations_id: jamaica.id)
Hotel.create(name: 'Montesol', destinations_id: grenada.id)
Hotel.create(name: 'Windjammer Landing', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'La Concha', destinations_id: st_lucia.id)
Hotel.create(name: 'Elea Beach', destinations_id: maldives.id)
Hotel.create(name: 'H10 Playas de Mallorca', destinations_id: male.id)
Hotel.create(name: 'Baia Azul', destinations_id: mauritius.id)
Hotel.create(name: 'Santa Eulalia Hotel & Spa', destinations_id: canaries.id)
Hotel.create(name: 'Servatur Canaima - Adult Only', destinations_id: fuerteventura.id)
Hotel.create(name: 'Avra Beach', destinations_id: antigua.id)
Hotel.create(name: 'Hotel Cellai', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Palau ca sa Galesa', destinations_id: corralejo.id)
Hotel.create(name: 'Vista Sol Punta Cana Beach Resort', destinations_id: costa_calma.id)
Hotel.create(name: 'Puro Hotel', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Quinta das Vistas Palace Gardens', destinations_id: gran_canaria.id)
Hotel.create(name: 'Mercure Nice Promenade des Anglais', destinations_id: arguineguin.id)
Hotel.create(name: 'Fergus Style Cala Blanca Suites', destinations_id: las_palmas.id)
Hotel.create(name: 'Vila Petra', destinations_id: maspalomas.id)
Hotel.create(name: 'Tivoli', destinations_id: meloneras.id)
Hotel.create(name: 'Mediterranean Palace Hotel', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Barcelo Castillo Beach Resort', destinations_id: puerto_rico.id)
Hotel.create(name: 'Maribel', destinations_id: san_agustin.id)
Hotel.create(name: 'Ondamar Hotel', destinations_id: sonnenland.id)
Hotel.create(name: 'Iberostar Lanzarote Park', destinations_id: lanzarote.id)
Hotel.create(name: 'San Francisco Park - Adults Only', destinations_id: costa_calero.id)
Hotel.create(name: 'Sol Sun Beach', destinations_id: costa_teguise.id)
Hotel.create(name: 'Rosy Apart', destinations_id: matagorda.id)
Hotel.create(name: 'Beis Beach', destinations_id: playa_blanca.id)
Hotel.create(name: 'Kyriad Nice Ouest Stade', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Club Hotel Riu Bachata', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Biniamar', destinations_id: tenerife.id)
Hotel.create(name: 'Parque Mourabel/Pe Do Lago/Oasis Village', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Govino Bay Apartments', destinations_id: costa_adeje.id)
Hotel.create(name: 'Luar', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Costa Mar', destinations_id: el_medano.id)
Hotel.create(name: 'HV Agaete Parque', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Mediodia', destinations_id: las_caletillas.id)
Hotel.create(name: 'Dunas Maspalomas', destinations_id: los_cristianos.id)
Hotel.create(name: 'AR Almerimar', destinations_id: playa_de_la_arena.id)
Hotel.create(name: "Grupotel Aldea Cala'n Bosch", destinations_id: playa_paraiso.id)
Hotel.create(name: 'Cerro da Marina', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Costa Mar', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Park Royal Cancun', destinations_id: santa_ursula.id)
Hotel.create(name: 'Vila Gale Atlantico', destinations_id: caribbean.id)
Hotel.create(name: 'Park Club Europe', destinations_id: bahamas.id)
Hotel.create(name: 'SBH Club Paraiso Playa', destinations_id: cayman_islands.id)
Hotel.create(name: 'Amathus Beach', destinations_id: bermuda.id)
Hotel.create(name: 'Kipriotis', destinations_id: barbados.id)
Hotel.create(name: 'Aguamarina Golf Hotel', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Montespina Park Hotel', destinations_id: cuba.id)
Hotel.create(name: 'Beverly Park', destinations_id: jamaica.id)
Hotel.create(name: "Costa d'Oiro Ambiance Village", destinations_id: grenada.id)
Hotel.create(name: 'Be Live Experience Playa La Arena', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Royal Plaza', destinations_id: st_lucia.id)
Hotel.create(name: 'Apartments Stella Jandia', destinations_id: maldives.id)
Hotel.create(name: 'Diverhotel Marbella', destinations_id: male.id)
Hotel.create(name: 'HSM Don Juan', destinations_id: mauritius.id)
Hotel.create(name: 'Labranda Hotel Tahona Garden', destinations_id: canaries.id)
Hotel.create(name: 'Crown', destinations_id: fuerteventura.id)
Hotel.create(name: 'Bagevleri', destinations_id: antigua.id)
Hotel.create(name: 'Comodoro', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Muthu Forte Da Oura', destinations_id: corralejo.id)
Hotel.create(name: 'Mitsis Grand Hotel Rhodes', destinations_id: costa_calma.id)
Hotel.create(name: 'Montebello', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Iberostar las Dalias', destinations_id: gran_canaria.id)
Hotel.create(name: 'Suite Fariones Playa', destinations_id: arguineguin.id)
Hotel.create(name: 'The Santa Maria Hotel', destinations_id: las_palmas.id)
Hotel.create(name: 'Gran Costa del Sol', destinations_id: maspalomas.id)
Hotel.create(name: 'Club Ciudadela', destinations_id: meloneras.id)
Hotel.create(name: 'Don Manolito', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Calas de Ibiza', destinations_id: puerto_rico.id)
Hotel.create(name: 'Labranda Bronze Playa', destinations_id: san_agustin.id)
Hotel.create(name: 'Marina Rio', destinations_id: sonnenland.id)
Hotel.create(name: 'Kensington', destinations_id: lanzarote.id)
Hotel.create(name: 'Myra Hotel', destinations_id: costa_calero.id)
Hotel.create(name: 'Imperial', destinations_id: costa_teguise.id)
Hotel.create(name: 'Hovima Costa Adeje', destinations_id: matagorda.id)
Hotel.create(name: 'Maritim', destinations_id: playa_blanca.id)
Hotel.create(name: 'Best Mojacar', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Fuerteventura Beach Club', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'The St. Georges Park Hotel', destinations_id: tenerife.id)
Hotel.create(name: 'Marbella Playa', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Saratoga', destinations_id: costa_adeje.id)
Hotel.create(name: 'Alta Galdana Hotel', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Aegean Princess Apartments', destinations_id: el_medano.id)
Hotel.create(name: 'AC Hotel Nice', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Mediterraneo Real', destinations_id: las_caletillas.id)
Hotel.create(name: 'Jimesol', destinations_id: los_cristianos.id)
Hotel.create(name: 'Palmera Mar Apartments', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Alagoamar', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Nido del Aguila', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Sol Don Marco', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Capri', destinations_id: santa_ursula.id)
Hotel.create(name: 'Rey Carlos', destinations_id: caribbean.id)
Hotel.create(name: 'Teix - Adults Only', destinations_id: bahamas.id)
Hotel.create(name: 'AC Gran Canaria', destinations_id: cayman_islands.id)
Hotel.create(name: 'Cala Nova', destinations_id: bermuda.id)
Hotel.create(name: 'Prinsotel la Dorada', destinations_id: barbados.id)
Hotel.create(name: 'Caribbean World Soma Bay', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Doria Hotel', destinations_id: cuba.id)
Hotel.create(name: 'Protur Atalaya', destinations_id: jamaica.id)
Hotel.create(name: 'Estrella de Mar', destinations_id: grenada.id)
Hotel.create(name: 'Real Bellavista Hotel & Spa', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Blue Sea Costa Teguise Beach', destinations_id: st_lucia.id)
Hotel.create(name: 'Golf Center Pueblo', destinations_id: maldives.id)
Hotel.create(name: 'Casa Colonial Beach & Spa', destinations_id: male.id)
Hotel.create(name: 'Muthu Raga', destinations_id: mauritius.id)
Hotel.create(name: 'Ola Club Panama', destinations_id: canaries.id)
Hotel.create(name: 'Massena', destinations_id: fuerteventura.id)
Hotel.create(name: 'San Giorgio e Olimpic', destinations_id: antigua.id)
Hotel.create(name: 'Il Palazzin', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Club Santa Ponsa', destinations_id: corralejo.id)
Hotel.create(name: 'Hipotels Flamenco', destinations_id: costa_calma.id)
Hotel.create(name: 'Vilar do Golf', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Don Pedro Apartments', destinations_id: gran_canaria.id)
Hotel.create(name: 'Prinsotel La Caleta Aparthotel', destinations_id: arguineguin.id)
Hotel.create(name: 'Mersoy Exclusive Aqua Resort', destinations_id: las_palmas.id)
Hotel.create(name: 'Adrian Hoteles Jardines de Nivaria', destinations_id: maspalomas.id)
Hotel.create(name: 'Alkan Hotel', destinations_id: meloneras.id)
Hotel.create(name: 'Palm Beach', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Fergus Tobago', destinations_id: puerto_rico.id)
Hotel.create(name: 'Vincci Selección Envía Almería Wellness & Golf', destinations_id: san_agustin.id)
Hotel.create(name: 'Hipotels Cala Millor Park', destinations_id: sonnenland.id)
Hotel.create(name: 'Horizonte', destinations_id: lanzarote.id)
Hotel.create(name: 'Hotel Alay', destinations_id: costa_calero.id)
Hotel.create(name: 'Paradis', destinations_id: costa_teguise.id)
Hotel.create(name: 'Zentral Center - Adults Only', destinations_id: matagorda.id)
Hotel.create(name: 'Richmond Ephesus', destinations_id: playa_blanca.id)
Hotel.create(name: 'Son Bou Gardens', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Osiris Ibiza', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Las Aguilas', destinations_id: tenerife.id)
Hotel.create(name: 'Catalonia Punta del Rey', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Tamisa Golf', destinations_id: costa_adeje.id)
Hotel.create(name: 'Zoraida Park', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Rural Sant Ignasi', destinations_id: el_medano.id)
Hotel.create(name: 'Sesin', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Bellevue Club', destinations_id: las_caletillas.id)
Hotel.create(name: 'Holiday Garden Village - Adults Only', destinations_id: los_cristianos.id)
Hotel.create(name: 'Great Parnassus Cancun', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Mac Puerto Marina Benalmadena', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Sunshine', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Carlota', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Royal Orchid', destinations_id: santa_ursula.id)
Hotel.create(name: 'Vasco da Gama', destinations_id: caribbean.id)
Hotel.create(name: 'Lydia Maris', destinations_id: bahamas.id)
Hotel.create(name: 'Cosmopolitan', destinations_id: cayman_islands.id)
Hotel.create(name: "Corinthia Hotel St George's Bay", destinations_id: bermuda.id)
Hotel.create(name: 'Xibana Park', destinations_id: barbados.id)
Hotel.create(name: 'Colina Mar', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Park Plaza Suites', destinations_id: cuba.id)
Hotel.create(name: 'Panorama', destinations_id: jamaica.id)
Hotel.create(name: 'Club Munamar Beach Resort', destinations_id: grenada.id)
Hotel.create(name: 'Abril Apartamentos', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Morasol Suites', destinations_id: st_lucia.id)
Hotel.create(name: 'Ekaterini Apartments', destinations_id: maldives.id)
Hotel.create(name: 'Castle Harbour', destinations_id: male.id)
Hotel.create(name: "Natalie's Beach", destinations_id: mauritius.id)
Hotel.create(name: 'Paraiso de Alcudia', destinations_id: canaries.id)
Hotel.create(name: 'Blue Sea Lagos De Cesar', destinations_id: fuerteventura.id)
Hotel.create(name: 'Grande Real Santa Eulalia Resort & Hotel Spa', destinations_id: antigua.id)
Hotel.create(name: 'SBH Costa Calma Beach', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Royal Solaris Cancun', destinations_id: corralejo.id)
Hotel.create(name: 'Pine Cliffs', destinations_id: costa_calma.id)
Hotel.create(name: 'Santa Catalina', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Vila Gale Marina', destinations_id: gran_canaria.id)
Hotel.create(name: 'Playa Pocillos', destinations_id: arguineguin.id)
Hotel.create(name: 'Balaia Atlantico', destinations_id: las_palmas.id)
Hotel.create(name: 'Pestana Alvor Atlantico', destinations_id: maspalomas.id)
Hotel.create(name: 'Doreta Beach', destinations_id: meloneras.id)
Hotel.create(name: 'Los Alamos', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Flatotel Internacional', destinations_id: puerto_rico.id)
Hotel.create(name: 'Parquemar', destinations_id: san_agustin.id)
Hotel.create(name: 'Vila Gale Ampalius', destinations_id: sonnenland.id)
Hotel.create(name: 'Ceylan Apart', destinations_id: lanzarote.id)
Hotel.create(name: 'Dawar el Omda', destinations_id: costa_calero.id)
Hotel.create(name: 'Celeste', destinations_id: costa_teguise.id)
Hotel.create(name: 'Villamar', destinations_id: matagorda.id)
Hotel.create(name: 'Baltum', destinations_id: playa_blanca.id)
Hotel.create(name: 'Cheerfulway Polana Residence', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Caleta Playa', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'San Giorgio', destinations_id: tenerife.id)
Hotel.create(name: 'Europa Apartments', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Armadams', destinations_id: costa_adeje.id)
Hotel.create(name: 'Parque Nogal', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Medplaya Hotel Bali', destinations_id: el_medano.id)
Hotel.create(name: 'Villa Marazul', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Apartments Fariones', destinations_id: las_caletillas.id)
Hotel.create(name: 'Florencio', destinations_id: los_cristianos.id)
Hotel.create(name: 'Neptuno', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Alanda Club Marbella', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Anba-Romani', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Azuline Hotel Bergantin', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Rayon Apart', destinations_id: santa_ursula.id)
Hotel.create(name: 'Arena Inn', destinations_id: caribbean.id)
Hotel.create(name: 'Atlantis Las Lomas', destinations_id: bahamas.id)
Hotel.create(name: 'Bungalows Castillo Playa', destinations_id: cayman_islands.id)
Hotel.create(name: 'Jable Bermudas', destinations_id: bermuda.id)
Hotel.create(name: 'Iberostar Playa de Muro Village', destinations_id: barbados.id)
Hotel.create(name: 'Fiesta Americana Gran Coral Beach Cancun', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Kilimanjaro', destinations_id: cuba.id)
Hotel.create(name: 'Tenerife Ving', destinations_id: jamaica.id)
Hotel.create(name: 'Montebello Splendid', destinations_id: grenada.id)
Hotel.create(name: 'Panoramic', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Labranda Oasis Mango Apartments', destinations_id: st_lucia.id)
Hotel.create(name: 'Set Hotel Port Mahon', destinations_id: maldives.id)
Hotel.create(name: 'Labranda Playa Club', destinations_id: male.id)
Hotel.create(name: 'Hotel Trianflor', destinations_id: mauritius.id)
Hotel.create(name: 'Villa Laredo', destinations_id: canaries.id)
Hotel.create(name: 'Three Corners Ocean View - Adults Only', destinations_id: fuerteventura.id)
Hotel.create(name: 'Marbel', destinations_id: antigua.id)
Hotel.create(name: 'Los Patos Park', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Grand Oasis Cancun', destinations_id: corralejo.id)
Hotel.create(name: 'IFA Buenaventura', destinations_id: costa_calma.id)
Hotel.create(name: 'Lopesan Villa del Conde Resort and Thalasso', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Cristal', destinations_id: gran_canaria.id)
Hotel.create(name: 'San Marcial', destinations_id: arguineguin.id)
Hotel.create(name: 'Tarik', destinations_id: las_palmas.id)
Hotel.create(name: 'Tivoli Lagos', destinations_id: maspalomas.id)
Hotel.create(name: 'Torrenueva Park', destinations_id: meloneras.id)
Hotel.create(name: 'Marina Club I', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Iberostar Jardin del Sol Suites - Adults Only', destinations_id: puerto_rico.id)
Hotel.create(name: 'Sandos Cancun Luxury Resort', destinations_id: san_agustin.id)
Hotel.create(name: 'Catalonia Oro Negro', destinations_id: sonnenland.id)
Hotel.create(name: 'Villas Corralejo', destinations_id: lanzarote.id)
Hotel.create(name: 'Ur Mision De San Miguel', destinations_id: costa_calero.id)
Hotel.create(name: 'Luna Holiday Complex', destinations_id: costa_teguise.id)
Hotel.create(name: 'Hotel Eurotel Altura', destinations_id: matagorda.id)
Hotel.create(name: 'Blue Sea Puerto Resort', destinations_id: playa_blanca.id)
Hotel.create(name: 'Oasis Papagayo', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Marquesa', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Livadi Nafsika', destinations_id: tenerife.id)
Hotel.create(name: 'Roc Lago Rojo', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Monica Isabel Beach Club', destinations_id: costa_adeje.id)
Hotel.create(name: 'TRYP Tenerife', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Veronica', destinations_id: el_medano.id)
Hotel.create(name: 'Omar', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Amazonas', destinations_id: las_caletillas.id)
Hotel.create(name: 'Hotel Palia La Roca', destinations_id: los_cristianos.id)
Hotel.create(name: 'Seashells Resort at Suncrest', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Los Ficus', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Playacapricho', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Mar Hotels Rosa del Mar & Spa 4*', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Gran Melia Victoria', destinations_id: santa_ursula.id)
Hotel.create(name: 'Las Buganvillas', destinations_id: caribbean.id)
Hotel.create(name: 'Fortina', destinations_id: bahamas.id)
Hotel.create(name: 'Santa Rosa', destinations_id: cayman_islands.id)
Hotel.create(name: 'Occidental Lanzarote Mar', destinations_id: bermuda.id)
Hotel.create(name: 'Catalonia las Vegas', destinations_id: barbados.id)
Hotel.create(name: 'Malibu Park', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'MGallery Cerretani Firenze', destinations_id: cuba.id)
Hotel.create(name: 'Club Sa Coma Apartments', destinations_id: jamaica.id)
Hotel.create(name: 'San Paolo', destinations_id: grenada.id)
Hotel.create(name: 'Paradise Park Fun Lifestyle Hotel', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Acuario Sol', destinations_id: st_lucia.id)
Hotel.create(name: 'Ocean Blue Sands Golf & Beach Resort', destinations_id: maldives.id)
Hotel.create(name: 'Folias', destinations_id: male.id)
Hotel.create(name: 'Vasari Resort', destinations_id: mauritius.id)
Hotel.create(name: 'Iberotel Makadi Oasis', destinations_id: canaries.id)
Hotel.create(name: 'Gran Sol', destinations_id: fuerteventura.id)
Hotel.create(name: 'Riu Palace Tenerife', destinations_id: antigua.id)
Hotel.create(name: 'El Lago', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Fergus Paraiso Beach - Adults Only', destinations_id: corralejo.id)
Hotel.create(name: 'Hotel Caribbean Bay', destinations_id: costa_calma.id)
Hotel.create(name: 'Paleo Art Nouveau', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Villa Victoria', destinations_id: gran_canaria.id)
Hotel.create(name: 'Hotel Serius', destinations_id: arguineguin.id)
Hotel.create(name: 'Valparaiso', destinations_id: las_palmas.id)
Hotel.create(name: 'Las Rampas', destinations_id: maspalomas.id)
Hotel.create(name: 'Orcagna', destinations_id: meloneras.id)
Hotel.create(name: 'Buenos Aires', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Brisa Sol', destinations_id: puerto_rico.id)
Hotel.create(name: 'Marivista', destinations_id: san_agustin.id)
Hotel.create(name: 'Beau Rivage', destinations_id: sonnenland.id)
Hotel.create(name: 'Arenal', destinations_id: lanzarote.id)
Hotel.create(name: 'Barceló Castillo Royal Level', destinations_id: costa_calero.id)
Hotel.create(name: 'Be Live Adults Only Tenerife', destinations_id: costa_teguise.id)
Hotel.create(name: 'Sol Guadalupe', destinations_id: matagorda.id)
Hotel.create(name: 'Hotel Golf Beach', destinations_id: playa_blanca.id)
Hotel.create(name: 'Lutania Beach', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Luz y Mar', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Don Bigote', destinations_id: tenerife.id)
Hotel.create(name: 'Serenity Makadi Beach', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Golden Orange', destinations_id: costa_adeje.id)
Hotel.create(name: 'Laguna Park II', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'My Dream', destinations_id: el_medano.id)
Hotel.create(name: 'Holiday Park', destinations_id: golf_del_sur.id)
Hotel.create(name: "Villas Cala'n Bosch", destinations_id: las_caletillas.id)
Hotel.create(name: 'Flora Aparthotel', destinations_id: los_cristianos.id)
Hotel.create(name: 'Palladium Hotel Palmyra - Adult Only', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Club Green Oasis Maspalomas', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Las Palomas Aptos.', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Fiesta Hotel Milord', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Sol Falco', destinations_id: santa_ursula.id)
Hotel.create(name: 'Cerro Mar Atlantico', destinations_id: caribbean.id)
Hotel.create(name: 'Strelitzias', destinations_id: bahamas.id)
Hotel.create(name: 'The BodyHoliday at Le Sport', destinations_id: cayman_islands.id)
Hotel.create(name: 'Formentera I', destinations_id: bermuda.id)
Hotel.create(name: 'Barcelo Fuerteventura Thalasso Spa', destinations_id: barbados.id)
Hotel.create(name: 'Anfora Playa', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Green Beach', destinations_id: cuba.id)
Hotel.create(name: 'Charisma De luxe', destinations_id: jamaica.id)
Hotel.create(name: 'Igramar Morro Jable', destinations_id: grenada.id)
Hotel.create(name: 'Batihan', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Turial Park', destinations_id: st_lucia.id)
Hotel.create(name: 'Blue Sea Los Fiscos', destinations_id: maldives.id)
Hotel.create(name: 'San Carlos', destinations_id: male.id)
Hotel.create(name: 'Tia Heights Makadi Bay', destinations_id: mauritius.id)
Hotel.create(name: 'Abora Catarina', destinations_id: canaries.id)
Hotel.create(name: 'Gorgulho', destinations_id: fuerteventura.id)
Hotel.create(name: 'Morasol Atlantico', destinations_id: antigua.id)
Hotel.create(name: 'Dorado Beach', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Nh Rambla de Alicante', destinations_id: corralejo.id)
Hotel.create(name: 'Fenix Family', destinations_id: costa_calma.id)
Hotel.create(name: 'Protur Palmeras Playa', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Azuline Hotel Galfi - Adults Only', destinations_id: gran_canaria.id)
Hotel.create(name: 'Santo Tomas', destinations_id: arguineguin.id)
Hotel.create(name: 'Intertur Apartments Waikiki', destinations_id: las_palmas.id)
Hotel.create(name: 'Melia Palas Atenea', destinations_id: maspalomas.id)
Hotel.create(name: 'Bellevue Vistanova', destinations_id: meloneras.id)
Hotel.create(name: 'Ozukara 2 Apartments', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Zafiro Palmanova', destinations_id: puerto_rico.id)
Hotel.create(name: 'Azuline Hotel Pacific', destinations_id: san_agustin.id)
Hotel.create(name: 'Sol Bahia', destinations_id: sonnenland.id)
Hotel.create(name: 'Kaan Apartments', destinations_id: lanzarote.id)
Hotel.create(name: 'West End', destinations_id: costa_calero.id)
Hotel.create(name: 'Vilabranca Apartments', destinations_id: costa_teguise.id)
Hotel.create(name: 'Hyatt Zilara Cancun - Adults Only', destinations_id: matagorda.id)
Hotel.create(name: 'Four Views Monumental', destinations_id: playa_blanca.id)
Hotel.create(name: 'Protur Biomar Gran Hotel & Spa', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Abrat', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Best Western Hotel Paradiso', destinations_id: tenerife.id)
Hotel.create(name: 'Xaloc', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Solar de Mos', destinations_id: costa_adeje.id)
Hotel.create(name: 'Monte Mar Palace', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Club Ako Apart', destinations_id: el_medano.id)
Hotel.create(name: 'Westin Resort & Spa Cancun', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Nice Excelsior – Chateaux & Hotels Collection', destinations_id: las_caletillas.id)
Hotel.create(name: 'Isla del Aire', destinations_id: los_cristianos.id)
Hotel.create(name: 'Deya', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Gran Melia Don Pepe', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Oceano Atlantico Turisticos Apartments', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Pestana Miramar', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Vitasol Park', destinations_id: santa_ursula.id)
Hotel.create(name: 'Grupotel Macarella', destinations_id: caribbean.id)
Hotel.create(name: 'Vidamar Resort Madeira', destinations_id: bahamas.id)
Hotel.create(name: 'Dom Manuel I', destinations_id: cayman_islands.id)
Hotel.create(name: 'Hotel Puerto de la Cruz', destinations_id: bermuda.id)
Hotel.create(name: 'Turquesa Beach', destinations_id: barbados.id)
Hotel.create(name: 'Aguabeach', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Voramar', destinations_id: cuba.id)
Hotel.create(name: 'Vista Dorada', destinations_id: jamaica.id)
Hotel.create(name: 'Los Monteros', destinations_id: grenada.id)
Hotel.create(name: 'Hovima Jardin Caleta', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Zodiaco', destinations_id: st_lucia.id)
Hotel.create(name: 'Grand Yazici Marmaris Palace', destinations_id: maldives.id)
Hotel.create(name: 'Saint Amon', destinations_id: male.id)
Hotel.create(name: 'Navy', destinations_id: mauritius.id)
Hotel.create(name: 'Riu Palmeras', destinations_id: canaries.id)
Hotel.create(name: 'Europe Playa Marina', destinations_id: fuerteventura.id)
Hotel.create(name: 'Cala Bona / Mar Blava', destinations_id: antigua.id)
Hotel.create(name: 'La Isla Y el mar hotel Boutique', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'San Agustin Beach Club', destinations_id: corralejo.id)
Hotel.create(name: 'Parque Tropical', destinations_id: costa_calma.id)
Hotel.create(name: 'Riu Merengue', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Meliá Jardines del Teide', destinations_id: gran_canaria.id)
Hotel.create(name: 'H10 Andalucia Plaza - Adults Only', destinations_id: arguineguin.id)
Hotel.create(name: 'Best Western hotel San Germano', destinations_id: las_palmas.id)
Hotel.create(name: 'Faro Jandia', destinations_id: maspalomas.id)
Hotel.create(name: 'Marina Palace', destinations_id: meloneras.id)
Hotel.create(name: 'Globales Sumba - Borneo', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Set Hotel Playa Azul', destinations_id: puerto_rico.id)
Hotel.create(name: 'Montemar', destinations_id: san_agustin.id)
Hotel.create(name: 'Cala Bona', destinations_id: sonnenland.id)
Hotel.create(name: 'Royal Al-Andalus', destinations_id: lanzarote.id)
Hotel.create(name: 'Veramar I', destinations_id: costa_calero.id)
Hotel.create(name: 'Condominios Salvia Cancun', destinations_id: costa_teguise.id)
Hotel.create(name: 'Grand Hotel Europa', destinations_id: matagorda.id)
Hotel.create(name: 'Blue Sea Interpalace', destinations_id: playa_blanca.id)
Hotel.create(name: 'Hotel Zhero-Hostal Deluxe', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Can Simo', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Vitalclass Lanzarote Sport Wellness Resort', destinations_id: tenerife.id)
Hotel.create(name: 'Quarteira Sol Hotel', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Seda Apart', destinations_id: costa_adeje.id)
Hotel.create(name: 'Tivoli Marina Vilamoura', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Pirates Village', destinations_id: el_medano.id)
Hotel.create(name: 'Korumar', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Ses Savines', destinations_id: las_caletillas.id)
Hotel.create(name: 'San Cristobal', destinations_id: los_cristianos.id)
Hotel.create(name: 'Aparthotel Imperatriz', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Olympic Palace', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Fanabe Costa Sur', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Hipotels Hipocampo Playa Apartments', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Globales Mimosa', destinations_id: santa_ursula.id)
Hotel.create(name: 'Adakule', destinations_id: caribbean.id)
Hotel.create(name: 'Sandos Papagayo Beach Resort', destinations_id: bahamas.id)
Hotel.create(name: 'Villa Florida', destinations_id: cayman_islands.id)
Hotel.create(name: 'Belmonte', destinations_id: bermuda.id)
Hotel.create(name: 'Negresco', destinations_id: barbados.id)
Hotel.create(name: 'Oasis Lanz Beach Mate', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Hotel Perla', destinations_id: cuba.id)
Hotel.create(name: 'Rodos Park Suites & Spa Hotel', destinations_id: jamaica.id)
Hotel.create(name: 'Fuengirola Beach', destinations_id: grenada.id)
Hotel.create(name: 'Maracaibo', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Marina Sao Roque', destinations_id: st_lucia.id)
Hotel.create(name: 'Sol House Ibiza', destinations_id: maldives.id)
Hotel.create(name: 'Quadra Key Residence', destinations_id: male.id)
Hotel.create(name: 'Carvoeiro Sol', destinations_id: mauritius.id)
Hotel.create(name: 'Nautilus Lanzarote', destinations_id: canaries.id)
Hotel.create(name: "Cala d'Or", destinations_id: fuerteventura.id)
Hotel.create(name: 'Villa Otero', destinations_id: antigua.id)
Hotel.create(name: 'Radisson Blu Resort', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Solferias', destinations_id: corralejo.id)
Hotel.create(name: 'Strozzi Palace Hotel', destinations_id: costa_calma.id)
Hotel.create(name: 'Bandama Bungalows', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Sur Menorca', destinations_id: gran_canaria.id)
Hotel.create(name: 'Monarque El Rodeo', destinations_id: arguineguin.id)
Hotel.create(name: 'Torrent Bay Club', destinations_id: las_palmas.id)
Hotel.create(name: 'Three Corners Rihana Resort', destinations_id: maspalomas.id)
Hotel.create(name: 'Hipotels Dunas', destinations_id: meloneras.id)
Hotel.create(name: 'NH Nice', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Fiesta Americana Condesa Cancun', destinations_id: puerto_rico.id)
Hotel.create(name: 'Sol Barbacan', destinations_id: san_agustin.id)
Hotel.create(name: 'Riosol', destinations_id: sonnenland.id)
Hotel.create(name: 'UR Azul Playa', destinations_id: lanzarote.id)
Hotel.create(name: 'Vista de Rey', destinations_id: costa_calero.id)
Hotel.create(name: 'Catalonia del Mar Hotel - Adults Only', destinations_id: costa_teguise.id)
Hotel.create(name: 'Don Carlos Leisure Resort & Spa', destinations_id: matagorda.id)
Hotel.create(name: 'Los Gracioseros', destinations_id: playa_blanca.id)
Hotel.create(name: 'Vila Gale Cerro Alagoa', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Nerja Club', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Alondras Park', destinations_id: tenerife.id)
Hotel.create(name: 'Globales Mediterrani Hotel', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Baia de Monte Gordo', destinations_id: costa_adeje.id)
Hotel.create(name: 'Lanzarote Village', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Sol Milanos-Pinguinos', destinations_id: el_medano.id)
Hotel.create(name: 'Hotel Cais da Oliveira', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Hotel Phoenicia', destinations_id: las_caletillas.id)
Hotel.create(name: 'Family Apart', destinations_id: los_cristianos.id)
Hotel.create(name: 'San Remo Hotel', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Villas Begonias', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Vila Gale Albacora', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Marte', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Reina Isabel', destinations_id: santa_ursula.id)
Hotel.create(name: 'Hotel Globales Acuario', destinations_id: caribbean.id)
Hotel.create(name: 'Select Benal Beach', destinations_id: bahamas.id)
Hotel.create(name: 'El Corso', destinations_id: cayman_islands.id)
Hotel.create(name: 'Ouratlantico', destinations_id: bermuda.id)
Hotel.create(name: 'Villa Rivoli', destinations_id: barbados.id)
Hotel.create(name: 'Royal Continental', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Residhome Nice Promenade', destinations_id: cuba.id)
Hotel.create(name: 'Kolymbia Star', destinations_id: jamaica.id)
Hotel.create(name: 'La Florida', destinations_id: grenada.id)
Hotel.create(name: 'Cancun Clipper Club', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Aguamar Apartments', destinations_id: st_lucia.id)
Hotel.create(name: 'San Francesco Al Monte', destinations_id: maldives.id)
Hotel.create(name: 'Hotel Troya', destinations_id: male.id)
Hotel.create(name: 'Club Mac Alcudia', destinations_id: mauritius.id)
Hotel.create(name: 'Bungalows Barranco', destinations_id: canaries.id)
Hotel.create(name: 'Las Marismas de Corralejo', destinations_id: fuerteventura.id)
Hotel.create(name: 'Gran Hotel Sol y Mar', destinations_id: antigua.id)
Hotel.create(name: 'Vista Club', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Terrazamar', destinations_id: corralejo.id)
Hotel.create(name: 'Pierre', destinations_id: costa_calma.id)
Hotel.create(name: 'Ria Park Garden', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Los Cactus', destinations_id: gran_canaria.id)
Hotel.create(name: 'Medano', destinations_id: arguineguin.id)
Hotel.create(name: 'Masaru', destinations_id: las_palmas.id)
Hotel.create(name: 'Viva Sunrise', destinations_id: maspalomas.id)
Hotel.create(name: 'Insotel Club Punta Prima', destinations_id: meloneras.id)
Hotel.create(name: 'Agla', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Juniper', destinations_id: puerto_rico.id)
Hotel.create(name: 'Inter-Hotel Le Lausanne', destinations_id: san_agustin.id)
Hotel.create(name: 'Louis Colossos Beach', destinations_id: sonnenland.id)
Hotel.create(name: 'Hotel de Flore Nice Promenade', destinations_id: lanzarote.id)
Hotel.create(name: 'Hotel THe Volcán Lanzarote', destinations_id: costa_calero.id)
Hotel.create(name: 'Apartaments Calma', destinations_id: costa_teguise.id)
Hotel.create(name: 'Fantasia Hotel De Luxe Kusadasi', destinations_id: matagorda.id)
Hotel.create(name: 'Ferrer Isabel', destinations_id: playa_blanca.id)
Hotel.create(name: 'Starhotel Terminus', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Castillo Hotel Son Vida', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Bungalows Las Vegas Golf', destinations_id: tenerife.id)
Hotel.create(name: 'Fuerte Marbella', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Mar y Huerta', destinations_id: costa_adeje.id)
Hotel.create(name: 'Club Montecastillo', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Oro Blanco Apartments', destinations_id: el_medano.id)
Hotel.create(name: 'Park Hotel', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Sunprime Cala Blanca', destinations_id: las_caletillas.id)
Hotel.create(name: 'IFA Faro', destinations_id: los_cristianos.id)
Hotel.create(name: 'ATH Roquetas de Mar', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Tryp Mallorca Santa Ponsa', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Maxorata Beach', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Aeolos Beach', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Riu Palace Tres Islas', destinations_id: santa_ursula.id)
Hotel.create(name: 'Palma Bay', destinations_id: caribbean.id)
Hotel.create(name: 'Occidental Margaritas', destinations_id: bahamas.id)
Hotel.create(name: 'Maxwell Holiday Club', destinations_id: cayman_islands.id)
Hotel.create(name: 'Girassol', destinations_id: bermuda.id)
Hotel.create(name: 'Best Siroco', destinations_id: barbados.id)
Hotel.create(name: 'Albergo Firenze', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Andorra Hotel and Apartments', destinations_id: cuba.id)
Hotel.create(name: 'Cay Beach Sun', destinations_id: jamaica.id)
Hotel.create(name: 'Hoposa Apartments Daina', destinations_id: grenada.id)
Hotel.create(name: 'Las Jacarandas', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Hard Rock Hotel Cancun', destinations_id: st_lucia.id)
Hotel.create(name: 'Zafiro Apartments', destinations_id: maldives.id)
Hotel.create(name: 'Punta del Mar - Adults Only', destinations_id: male.id)
Hotel.create(name: 'Toboso apar-turis', destinations_id: mauritius.id)
Hotel.create(name: 'Santa Clara', destinations_id: canaries.id)
Hotel.create(name: 'Lanzaplaya', destinations_id: fuerteventura.id)
Hotel.create(name: 'SunScape Dominican Beach', destinations_id: antigua.id)
Hotel.create(name: 'Camino Real', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Pueblo Torviscas', destinations_id: corralejo.id)
Hotel.create(name: 'Piscis', destinations_id: costa_calma.id)
Hotel.create(name: 'Ona Surfing Playa', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Luna Miramar', destinations_id: gran_canaria.id)
Hotel.create(name: 'Invisa Hotel Es Pla - Adults Only', destinations_id: arguineguin.id)
Hotel.create(name: 'Relaxia Olivina', destinations_id: las_palmas.id)
Hotel.create(name: 'Bungalows Parque Golf', destinations_id: maspalomas.id)
Hotel.create(name: 'Terrace Mar Suite', destinations_id: meloneras.id)
Hotel.create(name: 'Botel Alcudiamar', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Hamilton Court', destinations_id: puerto_rico.id)
Hotel.create(name: 'Mercure Nice Grimaldi', destinations_id: san_agustin.id)
Hotel.create(name: 'Globales Condes de Alcudia', destinations_id: sonnenland.id)
Hotel.create(name: 'Playa Bonita', destinations_id: lanzarote.id)
Hotel.create(name: 'Gran Palladium Bavaro Resort & Spa', destinations_id: costa_calero.id)
Hotel.create(name: 'Puerto Palace', destinations_id: costa_teguise.id)
Hotel.create(name: 'Ocean Gardens', destinations_id: matagorda.id)
Hotel.create(name: 'Praia Sol', destinations_id: playa_blanca.id)
Hotel.create(name: 'Sol Palmanova', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Servigroup Marina Mar', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Puerto Azul', destinations_id: tenerife.id)
Hotel.create(name: 'Majestic Colonial Punta Cana', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Sa Barrera', destinations_id: costa_adeje.id)
Hotel.create(name: 'Boscolo Astoria Florence', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Blue Palace Apart', destinations_id: el_medano.id)
Hotel.create(name: 'Occidental Jandia Mar', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Piscis - Adult Only', destinations_id: las_caletillas.id)
Hotel.create(name: 'Riu Monica', destinations_id: los_cristianos.id)
Hotel.create(name: 'Best Tenerife', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Playaflor Chill-Out Resort - Adults Only', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Denia Marriott La Sella Golf Resort & Spa', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Osborne', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Globales Lord Nelson - Adults Only', destinations_id: santa_ursula.id)
Hotel.create(name: 'HSM Canarios Park', destinations_id: caribbean.id)
Hotel.create(name: 'Aparthotel Reco des Sol Ibiza', destinations_id: bahamas.id)
Hotel.create(name: 'Corona Mar', destinations_id: cayman_islands.id)
Hotel.create(name: 'Club Eurocalas', destinations_id: bermuda.id)
Hotel.create(name: 'Isla de Lobos - Adults Only (16+)', destinations_id: barbados.id)
Hotel.create(name: 'More', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Villa Cesi', destinations_id: cuba.id)
Hotel.create(name: 'Tisalaya Park', destinations_id: jamaica.id)
Hotel.create(name: 'Villas La Bocaina', destinations_id: grenada.id)
Hotel.create(name: 'Best Western Alba Hotel', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Teror', destinations_id: st_lucia.id)
Hotel.create(name: 'Cinco Plazas', destinations_id: maldives.id)
Hotel.create(name: 'Hotel THe Fataga', destinations_id: male.id)
Hotel.create(name: 'Dassia Chandris', destinations_id: mauritius.id)
Hotel.create(name: 'db San Antonio Hotel + Spa', destinations_id: canaries.id)
Hotel.create(name: 'Grupotel Alcudia Suite', destinations_id: fuerteventura.id)
Hotel.create(name: 'Zafiro Rey Don Jaime', destinations_id: antigua.id)
Hotel.create(name: 'Sol Ponent', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Bungalows Miraflor Park', destinations_id: corralejo.id)
Hotel.create(name: 'Labranda Riviera Premium Resort and Spa', destinations_id: costa_calma.id)
Hotel.create(name: 'Puerta del Mar', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Vincci Tenerife Golf', destinations_id: gran_canaria.id)
Hotel.create(name: 'Hotel THB Ocean Beach - Adults Only', destinations_id: arguineguin.id)
Hotel.create(name: 'Gillieru Harbour', destinations_id: las_palmas.id)
Hotel.create(name: 'Vila Mos', destinations_id: maspalomas.id)
Hotel.create(name: 'Porto del Sol Apartments', destinations_id: meloneras.id)
Hotel.create(name: 'Crystal Admiral Resort', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Be Live Experience La Nina', destinations_id: puerto_rico.id)
Hotel.create(name: 'Avenida Praia', destinations_id: san_agustin.id)
Hotel.create(name: 'Jacaranda Hotel', destinations_id: sonnenland.id)
Hotel.create(name: 'Aquasol', destinations_id: lanzarote.id)
Hotel.create(name: 'Valparaiso Palace & Spa', destinations_id: costa_calero.id)
Hotel.create(name: 'Costa Calero', destinations_id: costa_teguise.id)
Hotel.create(name: 'El Faro Marbella Inn', destinations_id: matagorda.id)
Hotel.create(name: 'Paradisus Palma Real', destinations_id: playa_blanca.id)
Hotel.create(name: 'Athenaeum', destinations_id: puerto_del_carmen.id)
Hotel.create(name: "Reid's Palace", destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Popi Star Hotel', destinations_id: tenerife.id)
Hotel.create(name: 'Jardin del Atlantico', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Audax Spa & Wellness', destinations_id: costa_adeje.id)
Hotel.create(name: 'Hospes Amerigo', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'ATH Las Salinas Park Hotel', destinations_id: el_medano.id)
Hotel.create(name: 'Princesa Playa', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Best Triton', destinations_id: las_caletillas.id)
Hotel.create(name: 'BQ Augusta', destinations_id: los_cristianos.id)
Hotel.create(name: 'Labranda El Dorado Apartments', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'La Gioconda', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Rubino', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Fuertesol', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Santa Catarina', destinations_id: santa_ursula.id)
Hotel.create(name: 'Las Piramides', destinations_id: caribbean.id)
Hotel.create(name: 'NYX Hotel Cancun', destinations_id: bahamas.id)
Hotel.create(name: 'Cheerfulway Valmangude Jardim', destinations_id: cayman_islands.id)
Hotel.create(name: 'Enotel Lido Madeira', destinations_id: bermuda.id)
Hotel.create(name: 'Bahia Principe San Felipe', destinations_id: barbados.id)
Hotel.create(name: 'Marinasol', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Alfagar Village', destinations_id: cuba.id)
Hotel.create(name: 'Do Carmo', destinations_id: jamaica.id)
Hotel.create(name: 'Riu Belplaya', destinations_id: grenada.id)
Hotel.create(name: 'Complejo Los Pintores', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Grupotel Playa Club', destinations_id: st_lucia.id)
Hotel.create(name: 'Son Caliu Hotel Spa Oasis', destinations_id: maldives.id)
Hotel.create(name: 'Pez Azul', destinations_id: male.id)
Hotel.create(name: 'BelleVue Aquarius', destinations_id: mauritius.id)
Hotel.create(name: 'GR Solaris Cancun', destinations_id: canaries.id)
Hotel.create(name: 'Croce Di Malta', destinations_id: fuerteventura.id)
Hotel.create(name: 'Iberostar Punta Cana', destinations_id: antigua.id)
Hotel.create(name: 'Hotel Maritur - Adult Only', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Royal Garden Villas', destinations_id: corralejo.id)
Hotel.create(name: 'Achousa Studios', destinations_id: costa_calma.id)
Hotel.create(name: 'Dom Pedro Portobelo', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Los Pueblos', destinations_id: gran_canaria.id)
Hotel.create(name: 'Grand Hotel Le Florence', destinations_id: arguineguin.id)
Hotel.create(name: 'Playazul Apartments', destinations_id: las_palmas.id)
Hotel.create(name: 'Ketenci', destinations_id: maspalomas.id)
Hotel.create(name: 'Gran Melia de Mar - Adults Only', destinations_id: meloneras.id)
Hotel.create(name: 'Bahia del Sol', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Quinta da Bellavista', destinations_id: puerto_rico.id)
Hotel.create(name: 'Clube Praia Vau', destinations_id: san_agustin.id)
Hotel.create(name: 'SH Villa Gadea', destinations_id: sonnenland.id)
Hotel.create(name: 'Sun Grove Villas', destinations_id: lanzarote.id)
Hotel.create(name: 'db Seabank Resort & Spa', destinations_id: costa_calero.id)
Hotel.create(name: 'Los Olivos', destinations_id: costa_teguise.id)
Hotel.create(name: 'Bayside Salgados', destinations_id: matagorda.id)
Hotel.create(name: 'Alto Lido', destinations_id: playa_blanca.id)
Hotel.create(name: 'Tusan Beach Resort', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Angela', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Roc Lago Park', destinations_id: tenerife.id)
Hotel.create(name: 'Victoria Beach & Sports Hotel', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Be Live Family Costa de los Gigantes', destinations_id: costa_adeje.id)
Hotel.create(name: 'Seaside Los Jameos Playa Hotel', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Hovima Santa Maria', destinations_id: el_medano.id)
Hotel.create(name: 'Marina Playa Apartments', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Capistrano Villages', destinations_id: las_caletillas.id)
Hotel.create(name: 'Riu Garoe', destinations_id: los_cristianos.id)
Hotel.create(name: 'The San Anton Hotel', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Sentido Mallorca Palace - Adults Only', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Sensimar Arona Gran & Spa', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Pinhal do Sol', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Club Hotel Drago Park', destinations_id: santa_ursula.id)
Hotel.create(name: 'Cordial Sandy Golf', destinations_id: caribbean.id)
Hotel.create(name: 'Clube Oceano', destinations_id: bahamas.id)
Hotel.create(name: 'Habitat', destinations_id: cayman_islands.id)
Hotel.create(name: 'Riu Palace Jandia', destinations_id: bermuda.id)
Hotel.create(name: 'Lomeniz Beach', destinations_id: barbados.id)
Hotel.create(name: 'Gran Caribe Real Resort and Spa', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Meliá Gorriones Fuerteventura', destinations_id: cuba.id)
Hotel.create(name: 'Luna Clube Brisamar', destinations_id: jamaica.id)
Hotel.create(name: 'Faber Apart Hotel', destinations_id: grenada.id)
Hotel.create(name: 'Eugenia Victoria', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Alba', destinations_id: st_lucia.id)
Hotel.create(name: 'Olympus', destinations_id: maldives.id)
Hotel.create(name: 'Playaluna', destinations_id: male.id)
Hotel.create(name: 'Rio Playa Blanca', destinations_id: mauritius.id)
Hotel.create(name: 'Caleta Garden', destinations_id: canaries.id)
Hotel.create(name: 'Brisamar', destinations_id: fuerteventura.id)
Hotel.create(name: 'Hotel Jardin Tropical', destinations_id: antigua.id)
Hotel.create(name: 'Barceló Illetas Albatros - Adults Only', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Roc Golf Trinidad', destinations_id: corralejo.id)
Hotel.create(name: 'Playa Limones', destinations_id: costa_calma.id)
Hotel.create(name: 'TRH Jardin del Mar', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Alexandra Hotel', destinations_id: gran_canaria.id)
Hotel.create(name: 'Almar', destinations_id: arguineguin.id)
Hotel.create(name: 'TRYP Puerto De La Cruz', destinations_id: las_palmas.id)
Hotel.create(name: 'Iberostar Dominicana All Inclusive', destinations_id: maspalomas.id)
Hotel.create(name: 'Sentido Lanzarote Aequora Suites', destinations_id: meloneras.id)
Hotel.create(name: 'Sol e Mar', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Ponta Grande Resort', destinations_id: puerto_rico.id)
Hotel.create(name: 'Guacimeta', destinations_id: san_agustin.id)
Hotel.create(name: 'Teneguia', destinations_id: sonnenland.id)
Hotel.create(name: 'Samoa', destinations_id: lanzarote.id)
Hotel.create(name: 'Hotel Holiday Village', destinations_id: costa_calero.id)
Hotel.create(name: 'Sentido Castell de Mar', destinations_id: costa_teguise.id)
Hotel.create(name: 'Playa Dorada', destinations_id: matagorda.id)
Hotel.create(name: 'Althay', destinations_id: playa_blanca.id)
Hotel.create(name: 'Albufeira Jardim I y II', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'HM Jaime III', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Hilton Malta', destinations_id: tenerife.id)
Hotel.create(name: 'Omni Cancun & Villas', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Pestana Village', destinations_id: costa_adeje.id)
Hotel.create(name: 'Neptuno - Adults Only', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Spa Playasol', destinations_id: el_medano.id)
Hotel.create(name: 'Hotel Residencial Colina do Mar', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Los Dragos del Norte', destinations_id: las_caletillas.id)
Hotel.create(name: 'Paradise Cancun Resort and Spa', destinations_id: los_cristianos.id)
Hotel.create(name: 'Banana Apart', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Blue Sea Beach Resort', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Gran Ventana Beach Resort', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'SBH Crystal Beach', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Giada Florence', destinations_id: santa_ursula.id)
Hotel.create(name: 'Valle Mar', destinations_id: caribbean.id)
Hotel.create(name: 'Vilas Dinis - Adults Only', destinations_id: bahamas.id)
Hotel.create(name: 'Villa Medici', destinations_id: cayman_islands.id)
Hotel.create(name: 'Aquasol', destinations_id: bermuda.id)
Hotel.create(name: 'American Hotel', destinations_id: barbados.id)
Hotel.create(name: 'Side Star Park', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Primasud', destinations_id: cuba.id)
Hotel.create(name: 'Londra', destinations_id: jamaica.id)
Hotel.create(name: 'Barcelo Teguise Beach - Adults Only', destinations_id: grenada.id)
Hotel.create(name: 'Hesperia Bristol Playa', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Late Apartments', destinations_id: st_lucia.id)
Hotel.create(name: 'H10 Costa Adeje Palace', destinations_id: maldives.id)
Hotel.create(name: 'Villa Padierna Palace Hotel', destinations_id: male.id)
Hotel.create(name: 'Puerto Marina', destinations_id: mauritius.id)
Hotel.create(name: 'Regency Torviscas Apartments Suites', destinations_id: canaries.id)
Hotel.create(name: 'Melia Tamarindos', destinations_id: fuerteventura.id)
Hotel.create(name: 'Clube Praia da Rocha', destinations_id: antigua.id)
Hotel.create(name: 'Clube Porto Mos', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Sotavento', destinations_id: corralejo.id)
Hotel.create(name: 'A10 Sol de Alcudia Apartments', destinations_id: costa_calma.id)
Hotel.create(name: 'Parque Cattleya', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Playamar', destinations_id: gran_canaria.id)
Hotel.create(name: 'Globales Playa Santa Ponsa', destinations_id: arguineguin.id)
Hotel.create(name: 'Bahia Playa', destinations_id: las_palmas.id)
Hotel.create(name: 'Marina Suites', destinations_id: maspalomas.id)
Hotel.create(name: 'Varandas de Albufeira', destinations_id: meloneras.id)
Hotel.create(name: 'Club Riu Gran Canaria', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'H10 Timanfaya Palace - Adults Only', destinations_id: puerto_rico.id)
Hotel.create(name: 'Hotel Boreal', destinations_id: san_agustin.id)
Hotel.create(name: 'Hd Parque Cristobal Tenerife', destinations_id: sonnenland.id)
Hotel.create(name: 'Monaco Hotel', destinations_id: lanzarote.id)
Hotel.create(name: 'Flamingo Cancun Resort & Plaza', destinations_id: costa_calero.id)
Hotel.create(name: 'Relais Acropolis', destinations_id: costa_teguise.id)
Hotel.create(name: 'Louvre', destinations_id: matagorda.id)
Hotel.create(name: 'Hotel Flamboyan Caribe', destinations_id: playa_blanca.id)
Hotel.create(name: 'Castillo San Jorge, Antigua', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Pestana Casino Park', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Ole Tropical', destinations_id: tenerife.id)
Hotel.create(name: 'OH Marbella Inn', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Adriana Beach Club', destinations_id: costa_adeje.id)
Hotel.create(name: 'Plaza Cavana', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Mercure Angioino Centro', destinations_id: el_medano.id)
Hotel.create(name: 'Tropical Sol', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Geranios Suites & Spa', destinations_id: las_caletillas.id)
Hotel.create(name: 'Roc Costa Park', destinations_id: los_cristianos.id)
Hotel.create(name: 'IFA Beach Hotel - Adults Only', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Allegro Isora', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Janelas do Mar', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Cordial Green Golf', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Hotel Marco Polo - Adult Only', destinations_id: santa_ursula.id)
Hotel.create(name: 'Doramar', destinations_id: caribbean.id)
Hotel.create(name: 'Sabina', destinations_id: bahamas.id)
Hotel.create(name: 'The Kocer Beach Hotel', destinations_id: cayman_islands.id)
Hotel.create(name: 'Los Cardones', destinations_id: bermuda.id)
Hotel.create(name: 'Best Benalmadena', destinations_id: barbados.id)
Hotel.create(name: 'Maspalomas Oasis Club', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Barut Hotels Arum', destinations_id: cuba.id)
Hotel.create(name: 'Duva', destinations_id: jamaica.id)
Hotel.create(name: 'Capri', destinations_id: grenada.id)
Hotel.create(name: 'Blue Bay Getaway Villas Doradas', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: '4Dreams Hotel Chimisay', destinations_id: st_lucia.id)
Hotel.create(name: 'Correra 241', destinations_id: maldives.id)
Hotel.create(name: 'Dorado Suites Hotel', destinations_id: male.id)
Hotel.create(name: 'Palm Wings Ephesus Hotels And Resorts', destinations_id: mauritius.id)
Hotel.create(name: 'Guinate Club', destinations_id: canaries.id)
Hotel.create(name: 'Dom Pedro Baia Club', destinations_id: fuerteventura.id)
Hotel.create(name: 'Palm Garden', destinations_id: antigua.id)
Hotel.create(name: 'Playa Sur Tenerife', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Hotel Quinta Do Lago', destinations_id: corralejo.id)
Hotel.create(name: 'Hotel Blue Sea Don Jaime', destinations_id: costa_calma.id)
Hotel.create(name: 'Lagosmar', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Aloe', destinations_id: gran_canaria.id)
Hotel.create(name: 'Hotel RF Astoria - Adults Only', destinations_id: arguineguin.id)
Hotel.create(name: 'Topazio', destinations_id: las_palmas.id)
Hotel.create(name: 'Metropole', destinations_id: maspalomas.id)
Hotel.create(name: 'Casablanca - Adults Only', destinations_id: meloneras.id)
Hotel.create(name: 'Rocamar', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Escorial', destinations_id: puerto_rico.id)
Hotel.create(name: 'Sunset Beach Club', destinations_id: san_agustin.id)
Hotel.create(name: 'Iris', destinations_id: sonnenland.id)
Hotel.create(name: 'Idas Hotel', destinations_id: lanzarote.id)
Hotel.create(name: 'Montechoro', destinations_id: costa_calero.id)
Hotel.create(name: 'Jardins da Rocha', destinations_id: costa_teguise.id)
Hotel.create(name: 'Dom Pedro Lagos', destinations_id: matagorda.id)
Hotel.create(name: 'Blue Sky', destinations_id: playa_blanca.id)
Hotel.create(name: 'Hotel Jandia Golf', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Club Hotel Tropicana', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Alfamar Beach & Sport Resort', destinations_id: tenerife.id)
Hotel.create(name: 'El Puntazo', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Demircioglu Apart', destinations_id: costa_adeje.id)
Hotel.create(name: 'Bernini Palace', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Menorca Patricia', destinations_id: el_medano.id)
Hotel.create(name: 'Turbo Club', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Blue Sea Arenal Tower - Adult Only', destinations_id: las_caletillas.id)
Hotel.create(name: 'Park Plaza', destinations_id: los_cristianos.id)
Hotel.create(name: 'Le Meridien St. Julians', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Clube Alvorferias', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Los Arcos Montemar', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Sabina Playa', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Tropicana Studios', destinations_id: santa_ursula.id)
Hotel.create(name: 'Mansion de Nazaret', destinations_id: caribbean.id)
Hotel.create(name: 'Occidental Jandia Playa', destinations_id: bahamas.id)
Hotel.create(name: 'Sol House Costa del Sol', destinations_id: cayman_islands.id)
Hotel.create(name: 'Algarve Mor', destinations_id: bermuda.id)
Hotel.create(name: 'Annabels', destinations_id: barbados.id)
Hotel.create(name: 'Barcarola', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Vulcano', destinations_id: cuba.id)
Hotel.create(name: 'Casa del Sol', destinations_id: jamaica.id)
Hotel.create(name: 'Prainha Clube', destinations_id: grenada.id)
Hotel.create(name: 'Fergus Bermudas', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Topaz', destinations_id: st_lucia.id)
Hotel.create(name: 'Holiday Palace', destinations_id: maldives.id)
Hotel.create(name: 'Vistamar Aparthotel', destinations_id: male.id)
Hotel.create(name: 'Servatur Barbados', destinations_id: mauritius.id)
Hotel.create(name: 'Europa', destinations_id: canaries.id)
Hotel.create(name: 'Royal Savoy', destinations_id: fuerteventura.id)
Hotel.create(name: 'Hesperia Playa Dorada', destinations_id: antigua.id)
Hotel.create(name: 'Bay Gardens Inn', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Bungalows Coloradamar', destinations_id: corralejo.id)
Hotel.create(name: 'Villas del Sol', destinations_id: costa_calma.id)
Hotel.create(name: 'Harmony Suites', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Maris Beach', destinations_id: gran_canaria.id)
Hotel.create(name: 'Puerto Plata', destinations_id: arguineguin.id)
Hotel.create(name: 'Costa Canaria - Adults Only', destinations_id: las_palmas.id)
Hotel.create(name: 'Las Palmeras', destinations_id: maspalomas.id)
Hotel.create(name: 'Villa Flamenca', destinations_id: meloneras.id)
Hotel.create(name: 'All Sun Esquinzo Beach Hotel', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Corfu Chandris', destinations_id: puerto_rico.id)
Hotel.create(name: 'Grand Blue Sky International', destinations_id: san_agustin.id)
Hotel.create(name: 'Caledonia Park', destinations_id: sonnenland.id)
Hotel.create(name: 'Costa Sal', destinations_id: lanzarote.id)
Hotel.create(name: 'Continental', destinations_id: costa_calero.id)
Hotel.create(name: 'Seler', destinations_id: costa_teguise.id)
Hotel.create(name: "L'Ambiance", destinations_id: matagorda.id)
Hotel.create(name: 'Las Tejas', destinations_id: playa_blanca.id)
Hotel.create(name: 'Rosalia', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Neapolis', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'HSM President', destinations_id: tenerife.id)
Hotel.create(name: 'Vendome', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'Villas Salinas de Matagorda', destinations_id: costa_adeje.id)
Hotel.create(name: 'Fergus Style Pollensa Park', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Cantur City Hotel', destinations_id: el_medano.id)
Hotel.create(name: 'Riu Costa Lago', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Elegance', destinations_id: las_caletillas.id)
Hotel.create(name: 'Royal Panacea Hotel', destinations_id: los_cristianos.id)
Hotel.create(name: 'Juliani', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Grupotel Maritimo', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Sol Alcudia Center', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Pateo Village', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Hoposa Montelin', destinations_id: santa_ursula.id)
Hotel.create(name: 'Panorama - Adults Only', destinations_id: caribbean.id)
Hotel.create(name: 'Balaia Mar', destinations_id: bahamas.id)
Hotel.create(name: 'La Barracuda', destinations_id: cayman_islands.id)
Hotel.create(name: 'Isabel', destinations_id: bermuda.id)
Hotel.create(name: 'Golden Odyssey', destinations_id: barbados.id)
Hotel.create(name: 'Club Turkuaz', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Zafiro Bahia', destinations_id: cuba.id)
Hotel.create(name: "Illa d'Or", destinations_id: jamaica.id)
Hotel.create(name: 'Carema Beach Menorca (ex Siesta Playa)', destinations_id: grenada.id)
Hotel.create(name: 'Lima', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Mediterranean Hotel', destinations_id: st_lucia.id)
Hotel.create(name: 'Riu Arecas', destinations_id: maldives.id)
Hotel.create(name: 'Flor Da Laranja', destinations_id: male.id)
Hotel.create(name: 'Campanario de Calahonda', destinations_id: mauritius.id)
Hotel.create(name: 'Pasa Beach Hotel', destinations_id: canaries.id)
Hotel.create(name: 'Calamijas', destinations_id: fuerteventura.id)
Hotel.create(name: 'Akrotiri Beach', destinations_id: antigua.id)
Hotel.create(name: 'Club Simo Aparthotel', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Magna Grecia', destinations_id: corralejo.id)
Hotel.create(name: 'Delfin Casa Vida Apartments', destinations_id: costa_calma.id)
Hotel.create(name: 'Rex Hotel', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Beatriz Playa & Spa', destinations_id: gran_canaria.id)
Hotel.create(name: 'HL Club Playa Blanca', destinations_id: arguineguin.id)
Hotel.create(name: 'Relaxia Los Girasoles (Bungalows)', destinations_id: las_palmas.id)
Hotel.create(name: 'Ozadi Tavira Hotel', destinations_id: maspalomas.id)
Hotel.create(name: 'Estalagem Quinta da Casa Branca', destinations_id: meloneras.id)
Hotel.create(name: 'Aquamarina Beach Resort Hotel', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Zurbaran', destinations_id: puerto_rico.id)
Hotel.create(name: 'Julian Marmaris', destinations_id: san_agustin.id)
Hotel.create(name: 'Arena Center', destinations_id: sonnenland.id)
Hotel.create(name: 'Alp Hotel', destinations_id: lanzarote.id)
Hotel.create(name: 'Moon Palace', destinations_id: costa_calero.id)
Hotel.create(name: 'Apartamentos Royal Life', destinations_id: costa_teguise.id)
Hotel.create(name: 'Vistasur', destinations_id: matagorda.id)
Hotel.create(name: 'Aquis Palace Mon Repos - Adult Only', destinations_id: playa_blanca.id)
Hotel.create(name: 'Alondra Suites', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Vila Gale Praia - Adults Only', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Atlantis Apart', destinations_id: tenerife.id)
Hotel.create(name: 'Interpass Vauhotel Apartamentos', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'AC Ciutat de Palma', destinations_id: costa_adeje.id)
Hotel.create(name: 'Bluebay Banus', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'Sotavento', destinations_id: el_medano.id)
Hotel.create(name: 'Gran Bahia Principe Ambar - Adults Only', destinations_id: golf_del_sur.id)
Hotel.create(name: 'Pyr Fuengirola', destinations_id: las_caletillas.id)
Hotel.create(name: 'Riu Playa Cala Millor', destinations_id: los_cristianos.id)
Hotel.create(name: 'Cheerfulway California Hotel', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Grand Cettia', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Hotel Globales Pionero/Santa Ponsa Park', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Sur', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Kraft', destinations_id: santa_ursula.id)
Hotel.create(name: 'The Westin Dragonara Resort', destinations_id: caribbean.id)
Hotel.create(name: 'Bahia de Alcudia', destinations_id: bahamas.id)
Hotel.create(name: 'Monteparaiso', destinations_id: cayman_islands.id)
Hotel.create(name: 'Pine Cliffs Hotel, a Luxury Collection Resort', destinations_id: bermuda.id)
Hotel.create(name: 'Tabaiba / Maspalomas Princess', destinations_id: barbados.id)
Hotel.create(name: 'Sahara Playa', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: "Playas Ca's Saboners", destinations_id: cuba.id)
Hotel.create(name: 'Isla Mallorca', destinations_id: jamaica.id)
Hotel.create(name: 'Senses Palmanova - Adults Only', destinations_id: grenada.id)
Hotel.create(name: 'Hovima Atlantis', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Le Meridien Penina Golf & Resort', destinations_id: st_lucia.id)
Hotel.create(name: 'Grand Onder Hotel', destinations_id: maldives.id)
Hotel.create(name: 'Simbad', destinations_id: male.id)
Hotel.create(name: 'St. Lucian by Rex Resorts', destinations_id: mauritius.id)
Hotel.create(name: 'Los Nardos', destinations_id: canaries.id)
Hotel.create(name: 'Ibiscus Hotel', destinations_id: fuerteventura.id)
Hotel.create(name: 'Nuovo Rebecchino', destinations_id: antigua.id)
Hotel.create(name: 'Faro', destinations_id: caleta_de_fuste.id)
Hotel.create(name: 'Iberostar Marbella Coral Beach - Adult Only', destinations_id: corralejo.id)
Hotel.create(name: 'Club del Sol', destinations_id: costa_calma.id)
Hotel.create(name: 'Tortuga Bay', destinations_id: playa_de_jandia.id)
Hotel.create(name: 'Apartments THe Las Gaviotas', destinations_id: gran_canaria.id)
Hotel.create(name: 'HG Cala Llonga', destinations_id: arguineguin.id)
Hotel.create(name: 'La Reserva de Marbella', destinations_id: las_palmas.id)
Hotel.create(name: 'Playa del Ingles', destinations_id: maspalomas.id)
Hotel.create(name: 'Las Tartanas', destinations_id: meloneras.id)
Hotel.create(name: 'Pestana Palms', destinations_id: playa_del_ingles.id)
Hotel.create(name: 'Morana', destinations_id: puerto_rico.id)
Hotel.create(name: 'Iberostar Playa Gaviotas', destinations_id: san_agustin.id)
Hotel.create(name: 'IFA Interclub Atlantic', destinations_id: sonnenland.id)
Hotel.create(name: 'Excelsior', destinations_id: lanzarote.id)
Hotel.create(name: 'Bay Gardens Hotel', destinations_id: costa_calero.id)
Hotel.create(name: 'Buensol', destinations_id: costa_teguise.id)
Hotel.create(name: 'Meridmar Apart', destinations_id: matagorda.id)
Hotel.create(name: 'Globales Tamaimo Tropical', destinations_id: playa_blanca.id)
Hotel.create(name: 'Saint Gothard', destinations_id: puerto_del_carmen.id)
Hotel.create(name: 'Blancala', destinations_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Sheraton La Caleta Resort and Spa', destinations_id: tenerife.id)
Hotel.create(name: 'Hotel Jose Cruz', destinations_id: playa_de_las_americas.id)
Hotel.create(name: 'El Tope', destinations_id: costa_adeje.id)
Hotel.create(name: 'Brisa - Adults Only', destinations_id: costa_del_silencio.id)
Hotel.create(name: 'La Cala Resort', destinations_id: el_medano.id)
Hotel.create(name: 'Estalagem do Cerro', destinations_id: golf_del_sur.id)
Hotel.create(name: 'El Rodat', destinations_id: las_caletillas.id)
Hotel.create(name: 'Altamira', destinations_id: los_cristianos.id)
Hotel.create(name: 'Excellence Playa Mujeres - Adults Only', destinations_id: playa_de_la_arena.id)
Hotel.create(name: 'Vigilia Park', destinations_id: playa_paraiso.id)
Hotel.create(name: 'Vistamar', destinations_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Jandia Princess', destinations_id: puerto_santiago.id)
Hotel.create(name: 'Grand Hotel Minerva', destinations_id: santa_ursula.id)
Hotel.create(name: 'Arena', destinations_id: caribbean.id)
Hotel.create(name: 'Solemar', destinations_id: bahamas.id)
Hotel.create(name: 'Dom Pedro Marina', destinations_id: cayman_islands.id)
Hotel.create(name: 'Holiday Inn Resort Nice-Port St. Laurent', destinations_id: bermuda.id)
Hotel.create(name: 'Hotel Labranda Marieta', destinations_id: barbados.id)
Hotel.create(name: 'Servatur Hotel Puerto Azul', destinations_id: antigua_and_barbuda.id)
Hotel.create(name: 'Sol Don Pedro', destinations_id: cuba.id)
Hotel.create(name: 'Inagua', destinations_id: jamaica.id)
Hotel.create(name: 'Bellevue Lagomonte', destinations_id: grenada.id)
Hotel.create(name: 'R2 Rio Calma Hotel', destinations_id: trinidad_and_tobago.id)
Hotel.create(name: 'Atlantic Garden Beach Mate', destinations_id: st_lucia.id)
