maldives = Destination.find_by_name('Maldives')
male = Destination.find_by_name('Male')
mauritius = Destination.find_by_name('Mauritius')
canaries = Destination.find_by_name('Canaries')
fuerteventura = Destination.find_by_name('Fuerteventura')
antigua = Destination.find_by_name('Antigua')
caleta_de_fuste = Destination.find_by_name('Caleta De Fuste')
corralejo = Destination.find_by_name('Corralejo')
costa_calma = Destination.find_by_name('Costa Calma')
playa_de_jandia = Destination.find_by_name('Playa De Jandia')
gran_canaria = Destination.find_by_name('Gran Canaria')
arguineguin = Destination.find_by_name('Arguineguin')
las_palmas = Destination.find_by_name('Las Palmas')
maspalomas = Destination.find_by_name('Maspalomas')
meloneras = Destination.find_by_name('Meloneras')
playa_del_ingles = Destination.find_by_name('Playa Del Ingles')
puerto_rico = Destination.find_by_name('Puerto Rico')
san_agustin = Destination.find_by_name('San Agustin')
sonnenland = Destination.find_by_name('Sonnenland')
lanzarote = Destination.find_by_name('Lanzarote')
costa_calero = Destination.find_by_name('Costa Calero')
costa_teguise = Destination.find_by_name('Costa Teguise')
matagorda = Destination.find_by_name('Matagorda')
playa_blanca = Destination.find_by_name('Playa Blanca')
puerto_del_carmen = Destination.find_by_name('Puerto Del Carmen')
playa_de_los_pocillos = Destination.find_by_name('Playa De Los Pocillos')
tenerife = Destination.find_by_name('Tenerife')
playa_de_las_americas = Destination.find_by_name('Playa De Las Americas')
costa_adeje = Destination.find_by_name('Costa Adeje')
costa_del_silencio = Destination.find_by_name('Costa Del Silencio')
el_medano = Destination.find_by_name('El Medano')
golf_del_sur = Destination.find_by_name('Golf Del Sur')
las_caletillas = Destination.find_by_name('Las Caletillas')
los_cristianos = Destination.find_by_name('Los Cristianos')
playa_de_la_arena = Destination.find_by_name('Playa De La Arena')
playa_paraiso = Destination.find_by_name('Playa Paraiso')
puerto_de_la_cruz = Destination.find_by_name('Puerto De La Cruz')
puerto_santiago = Destination.find_by_name('Puerto Santiago')
santa_ursula = Destination.find_by_name('Santa Ursula')
caribbean = Destination.find_by_name('Caribbean')
bahamas = Destination.find_by_name('Bahamas')
cayman_islands = Destination.find_by_name('Cayman Islands')
bermuda = Destination.find_by_name('Bermuda')
barbados = Destination.find_by_name('Barbados')
antigua_and_barbuda = Destination.find_by_name('Antigua and Barbuda')
cuba = Destination.find_by_name('Cuba')
jamaica = Destination.find_by_name('Jamaica')
grenada = Destination.find_by_name('Grenada')
trinidad_and_tobago = Destination.find_by_name('Trinidad and Tobago')
st_lucia = Destination.find_by_name('St Lucia')

Hotel.create(name: 'Siesta I', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Servatur Waikiki', destination_id: el_medano.id)
Hotel.create(name: 'Grifone', destination_id: golf_del_sur.id)
Hotel.create(name: 'Blue Sea Costa Teguise Gardens', destination_id: las_caletillas.id)
Hotel.create(name: 'Gounod', destination_id: los_cristianos.id)
Hotel.create(name: 'Sultan Bey', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Kyriad Nice Centre Port', destination_id: playa_paraiso.id)
Hotel.create(name: 'Palia Las Palomas', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Playalinda', destination_id: puerto_santiago.id)
Hotel.create(name: 'Marina Bayview - Adult Only', destination_id: santa_ursula.id)
Hotel.create(name: 'Columbus Aparthotel', destination_id: caribbean.id)
Hotel.create(name: 'Zoraida Garden', destination_id: bahamas.id)
Hotel.create(name: 'Villas Santa Ana', destination_id: cayman_islands.id)
Hotel.create(name: 'SBH Fuerteventura Playa', destination_id: bermuda.id)
Hotel.create(name: 'Presidente', destination_id: barbados.id)
Hotel.create(name: 'Palazzo Alabardieri', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Teguisol', destination_id: cuba.id)
Hotel.create(name: 'Panorama', destination_id: jamaica.id)
Hotel.create(name: 'Montesol', destination_id: grenada.id)
Hotel.create(name: 'Windjammer Landing', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'La Concha', destination_id: st_lucia.id)
Hotel.create(name: 'Elea Beach', destination_id: maldives.id)
Hotel.create(name: 'H10 Playas de Mallorca', destination_id: male.id)
Hotel.create(name: 'Baia Azul', destination_id: mauritius.id)
Hotel.create(name: 'Santa Eulalia Hotel & Spa', destination_id: canaries.id)
Hotel.create(name: 'Servatur Canaima - Adult Only', destination_id: fuerteventura.id)
Hotel.create(name: 'Avra Beach', destination_id: antigua.id)
Hotel.create(name: 'Hotel Cellai', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Palau ca sa Galesa', destination_id: corralejo.id)
Hotel.create(name: 'Vista Sol Punta Cana Beach Resort', destination_id: costa_calma.id)
Hotel.create(name: 'Puro Hotel', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Quinta das Vistas Palace Gardens', destination_id: gran_canaria.id)
Hotel.create(name: 'Mercure Nice Promenade des Anglais', destination_id: arguineguin.id)
Hotel.create(name: 'Fergus Style Cala Blanca Suites', destination_id: las_palmas.id)
Hotel.create(name: 'Vila Petra', destination_id: maspalomas.id)
Hotel.create(name: 'Tivoli', destination_id: meloneras.id)
Hotel.create(name: 'Mediterranean Palace Hotel', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Barcelo Castillo Beach Resort', destination_id: puerto_rico.id)
Hotel.create(name: 'Maribel', destination_id: san_agustin.id)
Hotel.create(name: 'Ondamar Hotel', destination_id: sonnenland.id)
Hotel.create(name: 'Iberostar Lanzarote Park', destination_id: lanzarote.id)
Hotel.create(name: 'San Francisco Park - Adults Only', destination_id: costa_calero.id)
Hotel.create(name: 'Sol Sun Beach', destination_id: costa_teguise.id)
Hotel.create(name: 'Rosy Apart', destination_id: matagorda.id)
Hotel.create(name: 'Beis Beach', destination_id: playa_blanca.id)
Hotel.create(name: 'Kyriad Nice Ouest Stade', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Club Hotel Riu Bachata', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Biniamar', destination_id: tenerife.id)
Hotel.create(name: 'Parque Mourabel/Pe Do Lago/Oasis Village', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Govino Bay Apartments', destination_id: costa_adeje.id)
Hotel.create(name: 'Luar', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Costa Mar', destination_id: el_medano.id)
Hotel.create(name: 'HV Agaete Parque', destination_id: golf_del_sur.id)
Hotel.create(name: 'Mediodia', destination_id: las_caletillas.id)
Hotel.create(name: 'Dunas Maspalomas', destination_id: los_cristianos.id)
Hotel.create(name: 'AR Almerimar', destination_id: playa_de_la_arena.id)
Hotel.create(name: "Grupotel Aldea Cala'n Bosch", destination_id: playa_paraiso.id)
Hotel.create(name: 'Cerro da Marina', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Costa Mar', destination_id: puerto_santiago.id)
Hotel.create(name: 'Park Royal Cancun', destination_id: santa_ursula.id)
Hotel.create(name: 'Vila Gale Atlantico', destination_id: caribbean.id)
Hotel.create(name: 'Park Club Europe', destination_id: bahamas.id)
Hotel.create(name: 'SBH Club Paraiso Playa', destination_id: cayman_islands.id)
Hotel.create(name: 'Amathus Beach', destination_id: bermuda.id)
Hotel.create(name: 'Kipriotis', destination_id: barbados.id)
Hotel.create(name: 'Aguamarina Golf Hotel', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Montespina Park Hotel', destination_id: cuba.id)
Hotel.create(name: 'Beverly Park', destination_id: jamaica.id)
Hotel.create(name: "Costa d'Oiro Ambiance Village", destination_id: grenada.id)
Hotel.create(name: 'Be Live Experience Playa La Arena', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Royal Plaza', destination_id: st_lucia.id)
Hotel.create(name: 'Apartments Stella Jandia', destination_id: maldives.id)
Hotel.create(name: 'Diverhotel Marbella', destination_id: male.id)
Hotel.create(name: 'HSM Don Juan', destination_id: mauritius.id)
Hotel.create(name: 'Labranda Hotel Tahona Garden', destination_id: canaries.id)
Hotel.create(name: 'Crown', destination_id: fuerteventura.id)
Hotel.create(name: 'Bagevleri', destination_id: antigua.id)
Hotel.create(name: 'Comodoro', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Muthu Forte Da Oura', destination_id: corralejo.id)
Hotel.create(name: 'Mitsis Grand Hotel Rhodes', destination_id: costa_calma.id)
Hotel.create(name: 'Montebello', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Iberostar las Dalias', destination_id: gran_canaria.id)
Hotel.create(name: 'Suite Fariones Playa', destination_id: arguineguin.id)
Hotel.create(name: 'The Santa Maria Hotel', destination_id: las_palmas.id)
Hotel.create(name: 'Gran Costa del Sol', destination_id: maspalomas.id)
Hotel.create(name: 'Club Ciudadela', destination_id: meloneras.id)
Hotel.create(name: 'Don Manolito', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Calas de Ibiza', destination_id: puerto_rico.id)
Hotel.create(name: 'Labranda Bronze Playa', destination_id: san_agustin.id)
Hotel.create(name: 'Marina Rio', destination_id: sonnenland.id)
Hotel.create(name: 'Kensington', destination_id: lanzarote.id)
Hotel.create(name: 'Myra Hotel', destination_id: costa_calero.id)
Hotel.create(name: 'Imperial', destination_id: costa_teguise.id)
Hotel.create(name: 'Hovima Costa Adeje', destination_id: matagorda.id)
Hotel.create(name: 'Maritim', destination_id: playa_blanca.id)
Hotel.create(name: 'Best Mojacar', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Fuerteventura Beach Club', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'The St. Georges Park Hotel', destination_id: tenerife.id)
Hotel.create(name: 'Marbella Playa', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Saratoga', destination_id: costa_adeje.id)
Hotel.create(name: 'Alta Galdana Hotel', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Aegean Princess Apartments', destination_id: el_medano.id)
Hotel.create(name: 'AC Hotel Nice', destination_id: golf_del_sur.id)
Hotel.create(name: 'Mediterraneo Real', destination_id: las_caletillas.id)
Hotel.create(name: 'Jimesol', destination_id: los_cristianos.id)
Hotel.create(name: 'Palmera Mar Apartments', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Alagoamar', destination_id: playa_paraiso.id)
Hotel.create(name: 'Nido del Aguila', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Sol Don Marco', destination_id: puerto_santiago.id)
Hotel.create(name: 'Capri', destination_id: santa_ursula.id)
Hotel.create(name: 'Rey Carlos', destination_id: caribbean.id)
Hotel.create(name: 'Teix - Adults Only', destination_id: bahamas.id)
Hotel.create(name: 'AC Gran Canaria', destination_id: cayman_islands.id)
Hotel.create(name: 'Cala Nova', destination_id: bermuda.id)
Hotel.create(name: 'Prinsotel la Dorada', destination_id: barbados.id)
Hotel.create(name: 'Caribbean World Soma Bay', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Doria Hotel', destination_id: cuba.id)
Hotel.create(name: 'Protur Atalaya', destination_id: jamaica.id)
Hotel.create(name: 'Estrella de Mar', destination_id: grenada.id)
Hotel.create(name: 'Real Bellavista Hotel & Spa', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Blue Sea Costa Teguise Beach', destination_id: st_lucia.id)
Hotel.create(name: 'Golf Center Pueblo', destination_id: maldives.id)
Hotel.create(name: 'Casa Colonial Beach & Spa', destination_id: male.id)
Hotel.create(name: 'Muthu Raga', destination_id: mauritius.id)
Hotel.create(name: 'Ola Club Panama', destination_id: canaries.id)
Hotel.create(name: 'Massena', destination_id: fuerteventura.id)
Hotel.create(name: 'San Giorgio e Olimpic', destination_id: antigua.id)
Hotel.create(name: 'Il Palazzin', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Club Santa Ponsa', destination_id: corralejo.id)
Hotel.create(name: 'Hipotels Flamenco', destination_id: costa_calma.id)
Hotel.create(name: 'Vilar do Golf', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Don Pedro Apartments', destination_id: gran_canaria.id)
Hotel.create(name: 'Prinsotel La Caleta Aparthotel', destination_id: arguineguin.id)
Hotel.create(name: 'Mersoy Exclusive Aqua Resort', destination_id: las_palmas.id)
Hotel.create(name: 'Adrian Hoteles Jardines de Nivaria', destination_id: maspalomas.id)
Hotel.create(name: 'Alkan Hotel', destination_id: meloneras.id)
Hotel.create(name: 'Palm Beach', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Fergus Tobago', destination_id: puerto_rico.id)
Hotel.create(name: 'Vincci Selección Envía Almería Wellness & Golf', destination_id: san_agustin.id)
Hotel.create(name: 'Hipotels Cala Millor Park', destination_id: sonnenland.id)
Hotel.create(name: 'Horizonte', destination_id: lanzarote.id)
Hotel.create(name: 'Hotel Alay', destination_id: costa_calero.id)
Hotel.create(name: 'Paradis', destination_id: costa_teguise.id)
Hotel.create(name: 'Zentral Center - Adults Only', destination_id: matagorda.id)
Hotel.create(name: 'Richmond Ephesus', destination_id: playa_blanca.id)
Hotel.create(name: 'Son Bou Gardens', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Osiris Ibiza', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Las Aguilas', destination_id: tenerife.id)
Hotel.create(name: 'Catalonia Punta del Rey', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Tamisa Golf', destination_id: costa_adeje.id)
Hotel.create(name: 'Zoraida Park', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Rural Sant Ignasi', destination_id: el_medano.id)
Hotel.create(name: 'Sesin', destination_id: golf_del_sur.id)
Hotel.create(name: 'Bellevue Club', destination_id: las_caletillas.id)
Hotel.create(name: 'Holiday Garden Village - Adults Only', destination_id: los_cristianos.id)
Hotel.create(name: 'Great Parnassus Cancun', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Mac Puerto Marina Benalmadena', destination_id: playa_paraiso.id)
Hotel.create(name: 'Sunshine', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Carlota', destination_id: puerto_santiago.id)
Hotel.create(name: 'Royal Orchid', destination_id: santa_ursula.id)
Hotel.create(name: 'Vasco da Gama', destination_id: caribbean.id)
Hotel.create(name: 'Lydia Maris', destination_id: bahamas.id)
Hotel.create(name: 'Cosmopolitan', destination_id: cayman_islands.id)
Hotel.create(name: "Corinthia Hotel St George's Bay", destination_id: bermuda.id)
Hotel.create(name: 'Xibana Park', destination_id: barbados.id)
Hotel.create(name: 'Colina Mar', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Park Plaza Suites', destination_id: cuba.id)
Hotel.create(name: 'Panorama', destination_id: jamaica.id)
Hotel.create(name: 'Club Munamar Beach Resort', destination_id: grenada.id)
Hotel.create(name: 'Abril Apartamentos', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Morasol Suites', destination_id: st_lucia.id)
Hotel.create(name: 'Ekaterini Apartments', destination_id: maldives.id)
Hotel.create(name: 'Castle Harbour', destination_id: male.id)
Hotel.create(name: "Natalie's Beach", destination_id: mauritius.id)
Hotel.create(name: 'Paraiso de Alcudia', destination_id: canaries.id)
Hotel.create(name: 'Blue Sea Lagos De Cesar', destination_id: fuerteventura.id)
Hotel.create(name: 'Grande Real Santa Eulalia Resort & Hotel Spa', destination_id: antigua.id)
Hotel.create(name: 'SBH Costa Calma Beach', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Royal Solaris Cancun', destination_id: corralejo.id)
Hotel.create(name: 'Pine Cliffs', destination_id: costa_calma.id)
Hotel.create(name: 'Santa Catalina', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Vila Gale Marina', destination_id: gran_canaria.id)
Hotel.create(name: 'Playa Pocillos', destination_id: arguineguin.id)
Hotel.create(name: 'Balaia Atlantico', destination_id: las_palmas.id)
Hotel.create(name: 'Pestana Alvor Atlantico', destination_id: maspalomas.id)
Hotel.create(name: 'Doreta Beach', destination_id: meloneras.id)
Hotel.create(name: 'Los Alamos', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Flatotel Internacional', destination_id: puerto_rico.id)
Hotel.create(name: 'Parquemar', destination_id: san_agustin.id)
Hotel.create(name: 'Vila Gale Ampalius', destination_id: sonnenland.id)
Hotel.create(name: 'Ceylan Apart', destination_id: lanzarote.id)
Hotel.create(name: 'Dawar el Omda', destination_id: costa_calero.id)
Hotel.create(name: 'Celeste', destination_id: costa_teguise.id)
Hotel.create(name: 'Villamar', destination_id: matagorda.id)
Hotel.create(name: 'Baltum', destination_id: playa_blanca.id)
Hotel.create(name: 'Cheerfulway Polana Residence', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Caleta Playa', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'San Giorgio', destination_id: tenerife.id)
Hotel.create(name: 'Europa Apartments', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Armadams', destination_id: costa_adeje.id)
Hotel.create(name: 'Parque Nogal', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Medplaya Hotel Bali', destination_id: el_medano.id)
Hotel.create(name: 'Villa Marazul', destination_id: golf_del_sur.id)
Hotel.create(name: 'Apartments Fariones', destination_id: las_caletillas.id)
Hotel.create(name: 'Florencio', destination_id: los_cristianos.id)
Hotel.create(name: 'Neptuno', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Alanda Club Marbella', destination_id: playa_paraiso.id)
Hotel.create(name: 'Anba-Romani', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Azuline Hotel Bergantin', destination_id: puerto_santiago.id)
Hotel.create(name: 'Rayon Apart', destination_id: santa_ursula.id)
Hotel.create(name: 'Arena Inn', destination_id: caribbean.id)
Hotel.create(name: 'Atlantis Las Lomas', destination_id: bahamas.id)
Hotel.create(name: 'Bungalows Castillo Playa', destination_id: cayman_islands.id)
Hotel.create(name: 'Jable Bermudas', destination_id: bermuda.id)
Hotel.create(name: 'Iberostar Playa de Muro Village', destination_id: barbados.id)
Hotel.create(name: 'Fiesta Americana Gran Coral Beach Cancun', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Kilimanjaro', destination_id: cuba.id)
Hotel.create(name: 'Tenerife Ving', destination_id: jamaica.id)
Hotel.create(name: 'Montebello Splendid', destination_id: grenada.id)
Hotel.create(name: 'Panoramic', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Labranda Oasis Mango Apartments', destination_id: st_lucia.id)
Hotel.create(name: 'Set Hotel Port Mahon', destination_id: maldives.id)
Hotel.create(name: 'Labranda Playa Club', destination_id: male.id)
Hotel.create(name: 'Hotel Trianflor', destination_id: mauritius.id)
Hotel.create(name: 'Villa Laredo', destination_id: canaries.id)
Hotel.create(name: 'Three Corners Ocean View - Adults Only', destination_id: fuerteventura.id)
Hotel.create(name: 'Marbel', destination_id: antigua.id)
Hotel.create(name: 'Los Patos Park', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Grand Oasis Cancun', destination_id: corralejo.id)
Hotel.create(name: 'IFA Buenaventura', destination_id: costa_calma.id)
Hotel.create(name: 'Lopesan Villa del Conde Resort and Thalasso', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Cristal', destination_id: gran_canaria.id)
Hotel.create(name: 'San Marcial', destination_id: arguineguin.id)
Hotel.create(name: 'Tarik', destination_id: las_palmas.id)
Hotel.create(name: 'Tivoli Lagos', destination_id: maspalomas.id)
Hotel.create(name: 'Torrenueva Park', destination_id: meloneras.id)
Hotel.create(name: 'Marina Club I', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Iberostar Jardin del Sol Suites - Adults Only', destination_id: puerto_rico.id)
Hotel.create(name: 'Sandos Cancun Luxury Resort', destination_id: san_agustin.id)
Hotel.create(name: 'Catalonia Oro Negro', destination_id: sonnenland.id)
Hotel.create(name: 'Villas Corralejo', destination_id: lanzarote.id)
Hotel.create(name: 'Ur Mision De San Miguel', destination_id: costa_calero.id)
Hotel.create(name: 'Luna Holiday Complex', destination_id: costa_teguise.id)
Hotel.create(name: 'Hotel Eurotel Altura', destination_id: matagorda.id)
Hotel.create(name: 'Blue Sea Puerto Resort', destination_id: playa_blanca.id)
Hotel.create(name: 'Oasis Papagayo', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Marquesa', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Livadi Nafsika', destination_id: tenerife.id)
Hotel.create(name: 'Roc Lago Rojo', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Monica Isabel Beach Club', destination_id: costa_adeje.id)
Hotel.create(name: 'TRYP Tenerife', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Veronica', destination_id: el_medano.id)
Hotel.create(name: 'Omar', destination_id: golf_del_sur.id)
Hotel.create(name: 'Amazonas', destination_id: las_caletillas.id)
Hotel.create(name: 'Hotel Palia La Roca', destination_id: los_cristianos.id)
Hotel.create(name: 'Seashells Resort at Suncrest', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Los Ficus', destination_id: playa_paraiso.id)
Hotel.create(name: 'Playacapricho', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Mar Hotels Rosa del Mar & Spa 4*', destination_id: puerto_santiago.id)
Hotel.create(name: 'Gran Melia Victoria', destination_id: santa_ursula.id)
Hotel.create(name: 'Las Buganvillas', destination_id: caribbean.id)
Hotel.create(name: 'Fortina', destination_id: bahamas.id)
Hotel.create(name: 'Santa Rosa', destination_id: cayman_islands.id)
Hotel.create(name: 'Occidental Lanzarote Mar', destination_id: bermuda.id)
Hotel.create(name: 'Catalonia las Vegas', destination_id: barbados.id)
Hotel.create(name: 'Malibu Park', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'MGallery Cerretani Firenze', destination_id: cuba.id)
Hotel.create(name: 'Club Sa Coma Apartments', destination_id: jamaica.id)
Hotel.create(name: 'San Paolo', destination_id: grenada.id)
Hotel.create(name: 'Paradise Park Fun Lifestyle Hotel', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Acuario Sol', destination_id: st_lucia.id)
Hotel.create(name: 'Ocean Blue Sands Golf & Beach Resort', destination_id: maldives.id)
Hotel.create(name: 'Folias', destination_id: male.id)
Hotel.create(name: 'Vasari Resort', destination_id: mauritius.id)
Hotel.create(name: 'Iberotel Makadi Oasis', destination_id: canaries.id)
Hotel.create(name: 'Gran Sol', destination_id: fuerteventura.id)
Hotel.create(name: 'Riu Palace Tenerife', destination_id: antigua.id)
Hotel.create(name: 'El Lago', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Fergus Paraiso Beach - Adults Only', destination_id: corralejo.id)
Hotel.create(name: 'Hotel Caribbean Bay', destination_id: costa_calma.id)
Hotel.create(name: 'Paleo Art Nouveau', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Villa Victoria', destination_id: gran_canaria.id)
Hotel.create(name: 'Hotel Serius', destination_id: arguineguin.id)
Hotel.create(name: 'Valparaiso', destination_id: las_palmas.id)
Hotel.create(name: 'Las Rampas', destination_id: maspalomas.id)
Hotel.create(name: 'Orcagna', destination_id: meloneras.id)
Hotel.create(name: 'Buenos Aires', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Brisa Sol', destination_id: puerto_rico.id)
Hotel.create(name: 'Marivista', destination_id: san_agustin.id)
Hotel.create(name: 'Beau Rivage', destination_id: sonnenland.id)
Hotel.create(name: 'Arenal', destination_id: lanzarote.id)
Hotel.create(name: 'Barceló Castillo Royal Level', destination_id: costa_calero.id)
Hotel.create(name: 'Be Live Adults Only Tenerife', destination_id: costa_teguise.id)
Hotel.create(name: 'Sol Guadalupe', destination_id: matagorda.id)
Hotel.create(name: 'Hotel Golf Beach', destination_id: playa_blanca.id)
Hotel.create(name: 'Lutania Beach', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Luz y Mar', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Don Bigote', destination_id: tenerife.id)
Hotel.create(name: 'Serenity Makadi Beach', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Golden Orange', destination_id: costa_adeje.id)
Hotel.create(name: 'Laguna Park II', destination_id: costa_del_silencio.id)
Hotel.create(name: 'My Dream', destination_id: el_medano.id)
Hotel.create(name: 'Holiday Park', destination_id: golf_del_sur.id)
Hotel.create(name: "Villas Cala'n Bosch", destination_id: las_caletillas.id)
Hotel.create(name: 'Flora Aparthotel', destination_id: los_cristianos.id)
Hotel.create(name: 'Palladium Hotel Palmyra - Adult Only', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Club Green Oasis Maspalomas', destination_id: playa_paraiso.id)
Hotel.create(name: 'Las Palomas Aptos.', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Fiesta Hotel Milord', destination_id: puerto_santiago.id)
Hotel.create(name: 'Sol Falco', destination_id: santa_ursula.id)
Hotel.create(name: 'Cerro Mar Atlantico', destination_id: caribbean.id)
Hotel.create(name: 'Strelitzias', destination_id: bahamas.id)
Hotel.create(name: 'The BodyHoliday at Le Sport', destination_id: cayman_islands.id)
Hotel.create(name: 'Formentera I', destination_id: bermuda.id)
Hotel.create(name: 'Barcelo Fuerteventura Thalasso Spa', destination_id: barbados.id)
Hotel.create(name: 'Anfora Playa', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Green Beach', destination_id: cuba.id)
Hotel.create(name: 'Charisma De luxe', destination_id: jamaica.id)
Hotel.create(name: 'Igramar Morro Jable', destination_id: grenada.id)
Hotel.create(name: 'Batihan', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Turial Park', destination_id: st_lucia.id)
Hotel.create(name: 'Blue Sea Los Fiscos', destination_id: maldives.id)
Hotel.create(name: 'San Carlos', destination_id: male.id)
Hotel.create(name: 'Tia Heights Makadi Bay', destination_id: mauritius.id)
Hotel.create(name: 'Abora Catarina', destination_id: canaries.id)
Hotel.create(name: 'Gorgulho', destination_id: fuerteventura.id)
Hotel.create(name: 'Morasol Atlantico', destination_id: antigua.id)
Hotel.create(name: 'Dorado Beach', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Nh Rambla de Alicante', destination_id: corralejo.id)
Hotel.create(name: 'Fenix Family', destination_id: costa_calma.id)
Hotel.create(name: 'Protur Palmeras Playa', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Azuline Hotel Galfi - Adults Only', destination_id: gran_canaria.id)
Hotel.create(name: 'Santo Tomas', destination_id: arguineguin.id)
Hotel.create(name: 'Intertur Apartments Waikiki', destination_id: las_palmas.id)
Hotel.create(name: 'Melia Palas Atenea', destination_id: maspalomas.id)
Hotel.create(name: 'Bellevue Vistanova', destination_id: meloneras.id)
Hotel.create(name: 'Ozukara 2 Apartments', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Zafiro Palmanova', destination_id: puerto_rico.id)
Hotel.create(name: 'Azuline Hotel Pacific', destination_id: san_agustin.id)
Hotel.create(name: 'Sol Bahia', destination_id: sonnenland.id)
Hotel.create(name: 'Kaan Apartments', destination_id: lanzarote.id)
Hotel.create(name: 'West End', destination_id: costa_calero.id)
Hotel.create(name: 'Vilabranca Apartments', destination_id: costa_teguise.id)
Hotel.create(name: 'Hyatt Zilara Cancun - Adults Only', destination_id: matagorda.id)
Hotel.create(name: 'Four Views Monumental', destination_id: playa_blanca.id)
Hotel.create(name: 'Protur Biomar Gran Hotel & Spa', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Abrat', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Best Western Hotel Paradiso', destination_id: tenerife.id)
Hotel.create(name: 'Xaloc', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Solar de Mos', destination_id: costa_adeje.id)
Hotel.create(name: 'Monte Mar Palace', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Club Ako Apart', destination_id: el_medano.id)
Hotel.create(name: 'Westin Resort & Spa Cancun', destination_id: golf_del_sur.id)
Hotel.create(name: 'Nice Excelsior – Chateaux & Hotels Collection', destination_id: las_caletillas.id)
Hotel.create(name: 'Isla del Aire', destination_id: los_cristianos.id)
Hotel.create(name: 'Deya', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Gran Melia Don Pepe', destination_id: playa_paraiso.id)
Hotel.create(name: 'Oceano Atlantico Turisticos Apartments', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Pestana Miramar', destination_id: puerto_santiago.id)
Hotel.create(name: 'Vitasol Park', destination_id: santa_ursula.id)
Hotel.create(name: 'Grupotel Macarella', destination_id: caribbean.id)
Hotel.create(name: 'Vidamar Resort Madeira', destination_id: bahamas.id)
Hotel.create(name: 'Dom Manuel I', destination_id: cayman_islands.id)
Hotel.create(name: 'Hotel Puerto de la Cruz', destination_id: bermuda.id)
Hotel.create(name: 'Turquesa Beach', destination_id: barbados.id)
Hotel.create(name: 'Aguabeach', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Voramar', destination_id: cuba.id)
Hotel.create(name: 'Vista Dorada', destination_id: jamaica.id)
Hotel.create(name: 'Los Monteros', destination_id: grenada.id)
Hotel.create(name: 'Hovima Jardin Caleta', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Zodiaco', destination_id: st_lucia.id)
Hotel.create(name: 'Grand Yazici Marmaris Palace', destination_id: maldives.id)
Hotel.create(name: 'Saint Amon', destination_id: male.id)
Hotel.create(name: 'Navy', destination_id: mauritius.id)
Hotel.create(name: 'Riu Palmeras', destination_id: canaries.id)
Hotel.create(name: 'Europe Playa Marina', destination_id: fuerteventura.id)
Hotel.create(name: 'Cala Bona / Mar Blava', destination_id: antigua.id)
Hotel.create(name: 'La Isla Y el mar hotel Boutique', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'San Agustin Beach Club', destination_id: corralejo.id)
Hotel.create(name: 'Parque Tropical', destination_id: costa_calma.id)
Hotel.create(name: 'Riu Merengue', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Meliá Jardines del Teide', destination_id: gran_canaria.id)
Hotel.create(name: 'H10 Andalucia Plaza - Adults Only', destination_id: arguineguin.id)
Hotel.create(name: 'Best Western hotel San Germano', destination_id: las_palmas.id)
Hotel.create(name: 'Faro Jandia', destination_id: maspalomas.id)
Hotel.create(name: 'Marina Palace', destination_id: meloneras.id)
Hotel.create(name: 'Globales Sumba - Borneo', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Set Hotel Playa Azul', destination_id: puerto_rico.id)
Hotel.create(name: 'Montemar', destination_id: san_agustin.id)
Hotel.create(name: 'Cala Bona', destination_id: sonnenland.id)
Hotel.create(name: 'Royal Al-Andalus', destination_id: lanzarote.id)
Hotel.create(name: 'Veramar I', destination_id: costa_calero.id)
Hotel.create(name: 'Condominios Salvia Cancun', destination_id: costa_teguise.id)
Hotel.create(name: 'Grand Hotel Europa', destination_id: matagorda.id)
Hotel.create(name: 'Blue Sea Interpalace', destination_id: playa_blanca.id)
Hotel.create(name: 'Hotel Zhero-Hostal Deluxe', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Can Simo', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Vitalclass Lanzarote Sport Wellness Resort', destination_id: tenerife.id)
Hotel.create(name: 'Quarteira Sol Hotel', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Seda Apart', destination_id: costa_adeje.id)
Hotel.create(name: 'Tivoli Marina Vilamoura', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Pirates Village', destination_id: el_medano.id)
Hotel.create(name: 'Korumar', destination_id: golf_del_sur.id)
Hotel.create(name: 'Ses Savines', destination_id: las_caletillas.id)
Hotel.create(name: 'San Cristobal', destination_id: los_cristianos.id)
Hotel.create(name: 'Aparthotel Imperatriz', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Olympic Palace', destination_id: playa_paraiso.id)
Hotel.create(name: 'Fanabe Costa Sur', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Hipotels Hipocampo Playa Apartments', destination_id: puerto_santiago.id)
Hotel.create(name: 'Globales Mimosa', destination_id: santa_ursula.id)
Hotel.create(name: 'Adakule', destination_id: caribbean.id)
Hotel.create(name: 'Sandos Papagayo Beach Resort', destination_id: bahamas.id)
Hotel.create(name: 'Villa Florida', destination_id: cayman_islands.id)
Hotel.create(name: 'Belmonte', destination_id: bermuda.id)
Hotel.create(name: 'Negresco', destination_id: barbados.id)
Hotel.create(name: 'Oasis Lanz Beach Mate', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Hotel Perla', destination_id: cuba.id)
Hotel.create(name: 'Rodos Park Suites & Spa Hotel', destination_id: jamaica.id)
Hotel.create(name: 'Fuengirola Beach', destination_id: grenada.id)
Hotel.create(name: 'Maracaibo', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Marina Sao Roque', destination_id: st_lucia.id)
Hotel.create(name: 'Sol House Ibiza', destination_id: maldives.id)
Hotel.create(name: 'Quadra Key Residence', destination_id: male.id)
Hotel.create(name: 'Carvoeiro Sol', destination_id: mauritius.id)
Hotel.create(name: 'Nautilus Lanzarote', destination_id: canaries.id)
Hotel.create(name: "Cala d'Or", destination_id: fuerteventura.id)
Hotel.create(name: 'Villa Otero', destination_id: antigua.id)
Hotel.create(name: 'Radisson Blu Resort', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Solferias', destination_id: corralejo.id)
Hotel.create(name: 'Strozzi Palace Hotel', destination_id: costa_calma.id)
Hotel.create(name: 'Bandama Bungalows', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Sur Menorca', destination_id: gran_canaria.id)
Hotel.create(name: 'Monarque El Rodeo', destination_id: arguineguin.id)
Hotel.create(name: 'Torrent Bay Club', destination_id: las_palmas.id)
Hotel.create(name: 'Three Corners Rihana Resort', destination_id: maspalomas.id)
Hotel.create(name: 'Hipotels Dunas', destination_id: meloneras.id)
Hotel.create(name: 'NH Nice', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Fiesta Americana Condesa Cancun', destination_id: puerto_rico.id)
Hotel.create(name: 'Sol Barbacan', destination_id: san_agustin.id)
Hotel.create(name: 'Riosol', destination_id: sonnenland.id)
Hotel.create(name: 'UR Azul Playa', destination_id: lanzarote.id)
Hotel.create(name: 'Vista de Rey', destination_id: costa_calero.id)
Hotel.create(name: 'Catalonia del Mar Hotel - Adults Only', destination_id: costa_teguise.id)
Hotel.create(name: 'Don Carlos Leisure Resort & Spa', destination_id: matagorda.id)
Hotel.create(name: 'Los Gracioseros', destination_id: playa_blanca.id)
Hotel.create(name: 'Vila Gale Cerro Alagoa', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Nerja Club', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Alondras Park', destination_id: tenerife.id)
Hotel.create(name: 'Globales Mediterrani Hotel', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Baia de Monte Gordo', destination_id: costa_adeje.id)
Hotel.create(name: 'Lanzarote Village', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Sol Milanos-Pinguinos', destination_id: el_medano.id)
Hotel.create(name: 'Hotel Cais da Oliveira', destination_id: golf_del_sur.id)
Hotel.create(name: 'Hotel Phoenicia', destination_id: las_caletillas.id)
Hotel.create(name: 'Family Apart', destination_id: los_cristianos.id)
Hotel.create(name: 'San Remo Hotel', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Villas Begonias', destination_id: playa_paraiso.id)
Hotel.create(name: 'Vila Gale Albacora', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Marte', destination_id: puerto_santiago.id)
Hotel.create(name: 'Reina Isabel', destination_id: santa_ursula.id)
Hotel.create(name: 'Hotel Globales Acuario', destination_id: caribbean.id)
Hotel.create(name: 'Select Benal Beach', destination_id: bahamas.id)
Hotel.create(name: 'El Corso', destination_id: cayman_islands.id)
Hotel.create(name: 'Ouratlantico', destination_id: bermuda.id)
Hotel.create(name: 'Villa Rivoli', destination_id: barbados.id)
Hotel.create(name: 'Royal Continental', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Residhome Nice Promenade', destination_id: cuba.id)
Hotel.create(name: 'Kolymbia Star', destination_id: jamaica.id)
Hotel.create(name: 'La Florida', destination_id: grenada.id)
Hotel.create(name: 'Cancun Clipper Club', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Aguamar Apartments', destination_id: st_lucia.id)
Hotel.create(name: 'San Francesco Al Monte', destination_id: maldives.id)
Hotel.create(name: 'Hotel Troya', destination_id: male.id)
Hotel.create(name: 'Club Mac Alcudia', destination_id: mauritius.id)
Hotel.create(name: 'Bungalows Barranco', destination_id: canaries.id)
Hotel.create(name: 'Las Marismas de Corralejo', destination_id: fuerteventura.id)
Hotel.create(name: 'Gran Hotel Sol y Mar', destination_id: antigua.id)
Hotel.create(name: 'Vista Club', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Terrazamar', destination_id: corralejo.id)
Hotel.create(name: 'Pierre', destination_id: costa_calma.id)
Hotel.create(name: 'Ria Park Garden', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Los Cactus', destination_id: gran_canaria.id)
Hotel.create(name: 'Medano', destination_id: arguineguin.id)
Hotel.create(name: 'Masaru', destination_id: las_palmas.id)
Hotel.create(name: 'Viva Sunrise', destination_id: maspalomas.id)
Hotel.create(name: 'Insotel Club Punta Prima', destination_id: meloneras.id)
Hotel.create(name: 'Agla', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Juniper', destination_id: puerto_rico.id)
Hotel.create(name: 'Inter-Hotel Le Lausanne', destination_id: san_agustin.id)
Hotel.create(name: 'Louis Colossos Beach', destination_id: sonnenland.id)
Hotel.create(name: 'Hotel de Flore Nice Promenade', destination_id: lanzarote.id)
Hotel.create(name: 'Hotel THe Volcán Lanzarote', destination_id: costa_calero.id)
Hotel.create(name: 'Apartaments Calma', destination_id: costa_teguise.id)
Hotel.create(name: 'Fantasia Hotel De Luxe Kusadasi', destination_id: matagorda.id)
Hotel.create(name: 'Ferrer Isabel', destination_id: playa_blanca.id)
Hotel.create(name: 'Starhotel Terminus', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Castillo Hotel Son Vida', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Bungalows Las Vegas Golf', destination_id: tenerife.id)
Hotel.create(name: 'Fuerte Marbella', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Mar y Huerta', destination_id: costa_adeje.id)
Hotel.create(name: 'Club Montecastillo', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Oro Blanco Apartments', destination_id: el_medano.id)
Hotel.create(name: 'Park Hotel', destination_id: golf_del_sur.id)
Hotel.create(name: 'Sunprime Cala Blanca', destination_id: las_caletillas.id)
Hotel.create(name: 'IFA Faro', destination_id: los_cristianos.id)
Hotel.create(name: 'ATH Roquetas de Mar', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Tryp Mallorca Santa Ponsa', destination_id: playa_paraiso.id)
Hotel.create(name: 'Maxorata Beach', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Aeolos Beach', destination_id: puerto_santiago.id)
Hotel.create(name: 'Riu Palace Tres Islas', destination_id: santa_ursula.id)
Hotel.create(name: 'Palma Bay', destination_id: caribbean.id)
Hotel.create(name: 'Occidental Margaritas', destination_id: bahamas.id)
Hotel.create(name: 'Maxwell Holiday Club', destination_id: cayman_islands.id)
Hotel.create(name: 'Girassol', destination_id: bermuda.id)
Hotel.create(name: 'Best Siroco', destination_id: barbados.id)
Hotel.create(name: 'Albergo Firenze', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Andorra Hotel and Apartments', destination_id: cuba.id)
Hotel.create(name: 'Cay Beach Sun', destination_id: jamaica.id)
Hotel.create(name: 'Hoposa Apartments Daina', destination_id: grenada.id)
Hotel.create(name: 'Las Jacarandas', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Hard Rock Hotel Cancun', destination_id: st_lucia.id)
Hotel.create(name: 'Zafiro Apartments', destination_id: maldives.id)
Hotel.create(name: 'Punta del Mar - Adults Only', destination_id: male.id)
Hotel.create(name: 'Toboso apar-turis', destination_id: mauritius.id)
Hotel.create(name: 'Santa Clara', destination_id: canaries.id)
Hotel.create(name: 'Lanzaplaya', destination_id: fuerteventura.id)
Hotel.create(name: 'SunScape Dominican Beach', destination_id: antigua.id)
Hotel.create(name: 'Camino Real', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Pueblo Torviscas', destination_id: corralejo.id)
Hotel.create(name: 'Piscis', destination_id: costa_calma.id)
Hotel.create(name: 'Ona Surfing Playa', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Luna Miramar', destination_id: gran_canaria.id)
Hotel.create(name: 'Invisa Hotel Es Pla - Adults Only', destination_id: arguineguin.id)
Hotel.create(name: 'Relaxia Olivina', destination_id: las_palmas.id)
Hotel.create(name: 'Bungalows Parque Golf', destination_id: maspalomas.id)
Hotel.create(name: 'Terrace Mar Suite', destination_id: meloneras.id)
Hotel.create(name: 'Botel Alcudiamar', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Hamilton Court', destination_id: puerto_rico.id)
Hotel.create(name: 'Mercure Nice Grimaldi', destination_id: san_agustin.id)
Hotel.create(name: 'Globales Condes de Alcudia', destination_id: sonnenland.id)
Hotel.create(name: 'Playa Bonita', destination_id: lanzarote.id)
Hotel.create(name: 'Gran Palladium Bavaro Resort & Spa', destination_id: costa_calero.id)
Hotel.create(name: 'Puerto Palace', destination_id: costa_teguise.id)
Hotel.create(name: 'Ocean Gardens', destination_id: matagorda.id)
Hotel.create(name: 'Praia Sol', destination_id: playa_blanca.id)
Hotel.create(name: 'Sol Palmanova', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Servigroup Marina Mar', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Puerto Azul', destination_id: tenerife.id)
Hotel.create(name: 'Majestic Colonial Punta Cana', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Sa Barrera', destination_id: costa_adeje.id)
Hotel.create(name: 'Boscolo Astoria Florence', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Blue Palace Apart', destination_id: el_medano.id)
Hotel.create(name: 'Occidental Jandia Mar', destination_id: golf_del_sur.id)
Hotel.create(name: 'Piscis - Adult Only', destination_id: las_caletillas.id)
Hotel.create(name: 'Riu Monica', destination_id: los_cristianos.id)
Hotel.create(name: 'Best Tenerife', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Playaflor Chill-Out Resort - Adults Only', destination_id: playa_paraiso.id)
Hotel.create(name: 'Denia Marriott La Sella Golf Resort & Spa', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Osborne', destination_id: puerto_santiago.id)
Hotel.create(name: 'Globales Lord Nelson - Adults Only', destination_id: santa_ursula.id)
Hotel.create(name: 'HSM Canarios Park', destination_id: caribbean.id)
Hotel.create(name: 'Aparthotel Reco des Sol Ibiza', destination_id: bahamas.id)
Hotel.create(name: 'Corona Mar', destination_id: cayman_islands.id)
Hotel.create(name: 'Club Eurocalas', destination_id: bermuda.id)
Hotel.create(name: 'Isla de Lobos - Adults Only (16+)', destination_id: barbados.id)
Hotel.create(name: 'More', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Villa Cesi', destination_id: cuba.id)
Hotel.create(name: 'Tisalaya Park', destination_id: jamaica.id)
Hotel.create(name: 'Villas La Bocaina', destination_id: grenada.id)
Hotel.create(name: 'Best Western Alba Hotel', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Teror', destination_id: st_lucia.id)
Hotel.create(name: 'Cinco Plazas', destination_id: maldives.id)
Hotel.create(name: 'Hotel THe Fataga', destination_id: male.id)
Hotel.create(name: 'Dassia Chandris', destination_id: mauritius.id)
Hotel.create(name: 'db San Antonio Hotel + Spa', destination_id: canaries.id)
Hotel.create(name: 'Grupotel Alcudia Suite', destination_id: fuerteventura.id)
Hotel.create(name: 'Zafiro Rey Don Jaime', destination_id: antigua.id)
Hotel.create(name: 'Sol Ponent', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Bungalows Miraflor Park', destination_id: corralejo.id)
Hotel.create(name: 'Labranda Riviera Premium Resort and Spa', destination_id: costa_calma.id)
Hotel.create(name: 'Puerta del Mar', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Vincci Tenerife Golf', destination_id: gran_canaria.id)
Hotel.create(name: 'Hotel THB Ocean Beach - Adults Only', destination_id: arguineguin.id)
Hotel.create(name: 'Gillieru Harbour', destination_id: las_palmas.id)
Hotel.create(name: 'Vila Mos', destination_id: maspalomas.id)
Hotel.create(name: 'Porto del Sol Apartments', destination_id: meloneras.id)
Hotel.create(name: 'Crystal Admiral Resort', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Be Live Experience La Nina', destination_id: puerto_rico.id)
Hotel.create(name: 'Avenida Praia', destination_id: san_agustin.id)
Hotel.create(name: 'Jacaranda Hotel', destination_id: sonnenland.id)
Hotel.create(name: 'Aquasol', destination_id: lanzarote.id)
Hotel.create(name: 'Valparaiso Palace & Spa', destination_id: costa_calero.id)
Hotel.create(name: 'Costa Calero', destination_id: costa_teguise.id)
Hotel.create(name: 'El Faro Marbella Inn', destination_id: matagorda.id)
Hotel.create(name: 'Paradisus Palma Real', destination_id: playa_blanca.id)
Hotel.create(name: 'Athenaeum', destination_id: puerto_del_carmen.id)
Hotel.create(name: "Reid's Palace", destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Popi Star Hotel', destination_id: tenerife.id)
Hotel.create(name: 'Jardin del Atlantico', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Audax Spa & Wellness', destination_id: costa_adeje.id)
Hotel.create(name: 'Hospes Amerigo', destination_id: costa_del_silencio.id)
Hotel.create(name: 'ATH Las Salinas Park Hotel', destination_id: el_medano.id)
Hotel.create(name: 'Princesa Playa', destination_id: golf_del_sur.id)
Hotel.create(name: 'Best Triton', destination_id: las_caletillas.id)
Hotel.create(name: 'BQ Augusta', destination_id: los_cristianos.id)
Hotel.create(name: 'Labranda El Dorado Apartments', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'La Gioconda', destination_id: playa_paraiso.id)
Hotel.create(name: 'Rubino', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Fuertesol', destination_id: puerto_santiago.id)
Hotel.create(name: 'Santa Catarina', destination_id: santa_ursula.id)
Hotel.create(name: 'Las Piramides', destination_id: caribbean.id)
Hotel.create(name: 'NYX Hotel Cancun', destination_id: bahamas.id)
Hotel.create(name: 'Cheerfulway Valmangude Jardim', destination_id: cayman_islands.id)
Hotel.create(name: 'Enotel Lido Madeira', destination_id: bermuda.id)
Hotel.create(name: 'Bahia Principe San Felipe', destination_id: barbados.id)
Hotel.create(name: 'Marinasol', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Alfagar Village', destination_id: cuba.id)
Hotel.create(name: 'Do Carmo', destination_id: jamaica.id)
Hotel.create(name: 'Riu Belplaya', destination_id: grenada.id)
Hotel.create(name: 'Complejo Los Pintores', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Grupotel Playa Club', destination_id: st_lucia.id)
Hotel.create(name: 'Son Caliu Hotel Spa Oasis', destination_id: maldives.id)
Hotel.create(name: 'Pez Azul', destination_id: male.id)
Hotel.create(name: 'BelleVue Aquarius', destination_id: mauritius.id)
Hotel.create(name: 'GR Solaris Cancun', destination_id: canaries.id)
Hotel.create(name: 'Croce Di Malta', destination_id: fuerteventura.id)
Hotel.create(name: 'Iberostar Punta Cana', destination_id: antigua.id)
Hotel.create(name: 'Hotel Maritur - Adult Only', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Royal Garden Villas', destination_id: corralejo.id)
Hotel.create(name: 'Achousa Studios', destination_id: costa_calma.id)
Hotel.create(name: 'Dom Pedro Portobelo', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Los Pueblos', destination_id: gran_canaria.id)
Hotel.create(name: 'Grand Hotel Le Florence', destination_id: arguineguin.id)
Hotel.create(name: 'Playazul Apartments', destination_id: las_palmas.id)
Hotel.create(name: 'Ketenci', destination_id: maspalomas.id)
Hotel.create(name: 'Gran Melia de Mar - Adults Only', destination_id: meloneras.id)
Hotel.create(name: 'Bahia del Sol', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Quinta da Bellavista', destination_id: puerto_rico.id)
Hotel.create(name: 'Clube Praia Vau', destination_id: san_agustin.id)
Hotel.create(name: 'SH Villa Gadea', destination_id: sonnenland.id)
Hotel.create(name: 'Sun Grove Villas', destination_id: lanzarote.id)
Hotel.create(name: 'db Seabank Resort & Spa', destination_id: costa_calero.id)
Hotel.create(name: 'Los Olivos', destination_id: costa_teguise.id)
Hotel.create(name: 'Bayside Salgados', destination_id: matagorda.id)
Hotel.create(name: 'Alto Lido', destination_id: playa_blanca.id)
Hotel.create(name: 'Tusan Beach Resort', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Angela', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Roc Lago Park', destination_id: tenerife.id)
Hotel.create(name: 'Victoria Beach & Sports Hotel', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Be Live Family Costa de los Gigantes', destination_id: costa_adeje.id)
Hotel.create(name: 'Seaside Los Jameos Playa Hotel', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Hovima Santa Maria', destination_id: el_medano.id)
Hotel.create(name: 'Marina Playa Apartments', destination_id: golf_del_sur.id)
Hotel.create(name: 'Capistrano Villages', destination_id: las_caletillas.id)
Hotel.create(name: 'Riu Garoe', destination_id: los_cristianos.id)
Hotel.create(name: 'The San Anton Hotel', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Sentido Mallorca Palace - Adults Only', destination_id: playa_paraiso.id)
Hotel.create(name: 'Sensimar Arona Gran & Spa', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Pinhal do Sol', destination_id: puerto_santiago.id)
Hotel.create(name: 'Club Hotel Drago Park', destination_id: santa_ursula.id)
Hotel.create(name: 'Cordial Sandy Golf', destination_id: caribbean.id)
Hotel.create(name: 'Clube Oceano', destination_id: bahamas.id)
Hotel.create(name: 'Habitat', destination_id: cayman_islands.id)
Hotel.create(name: 'Riu Palace Jandia', destination_id: bermuda.id)
Hotel.create(name: 'Lomeniz Beach', destination_id: barbados.id)
Hotel.create(name: 'Gran Caribe Real Resort and Spa', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Meliá Gorriones Fuerteventura', destination_id: cuba.id)
Hotel.create(name: 'Luna Clube Brisamar', destination_id: jamaica.id)
Hotel.create(name: 'Faber Apart Hotel', destination_id: grenada.id)
Hotel.create(name: 'Eugenia Victoria', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Alba', destination_id: st_lucia.id)
Hotel.create(name: 'Olympus', destination_id: maldives.id)
Hotel.create(name: 'Playaluna', destination_id: male.id)
Hotel.create(name: 'Rio Playa Blanca', destination_id: mauritius.id)
Hotel.create(name: 'Caleta Garden', destination_id: canaries.id)
Hotel.create(name: 'Brisamar', destination_id: fuerteventura.id)
Hotel.create(name: 'Hotel Jardin Tropical', destination_id: antigua.id)
Hotel.create(name: 'Barceló Illetas Albatros - Adults Only', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Roc Golf Trinidad', destination_id: corralejo.id)
Hotel.create(name: 'Playa Limones', destination_id: costa_calma.id)
Hotel.create(name: 'TRH Jardin del Mar', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Alexandra Hotel', destination_id: gran_canaria.id)
Hotel.create(name: 'Almar', destination_id: arguineguin.id)
Hotel.create(name: 'TRYP Puerto De La Cruz', destination_id: las_palmas.id)
Hotel.create(name: 'Iberostar Dominicana All Inclusive', destination_id: maspalomas.id)
Hotel.create(name: 'Sentido Lanzarote Aequora Suites', destination_id: meloneras.id)
Hotel.create(name: 'Sol e Mar', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Ponta Grande Resort', destination_id: puerto_rico.id)
Hotel.create(name: 'Guacimeta', destination_id: san_agustin.id)
Hotel.create(name: 'Teneguia', destination_id: sonnenland.id)
Hotel.create(name: 'Samoa', destination_id: lanzarote.id)
Hotel.create(name: 'Hotel Holiday Village', destination_id: costa_calero.id)
Hotel.create(name: 'Sentido Castell de Mar', destination_id: costa_teguise.id)
Hotel.create(name: 'Playa Dorada', destination_id: matagorda.id)
Hotel.create(name: 'Althay', destination_id: playa_blanca.id)
Hotel.create(name: 'Albufeira Jardim I y II', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'HM Jaime III', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Hilton Malta', destination_id: tenerife.id)
Hotel.create(name: 'Omni Cancun & Villas', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Pestana Village', destination_id: costa_adeje.id)
Hotel.create(name: 'Neptuno - Adults Only', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Spa Playasol', destination_id: el_medano.id)
Hotel.create(name: 'Hotel Residencial Colina do Mar', destination_id: golf_del_sur.id)
Hotel.create(name: 'Los Dragos del Norte', destination_id: las_caletillas.id)
Hotel.create(name: 'Paradise Cancun Resort and Spa', destination_id: los_cristianos.id)
Hotel.create(name: 'Banana Apart', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Blue Sea Beach Resort', destination_id: playa_paraiso.id)
Hotel.create(name: 'Gran Ventana Beach Resort', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'SBH Crystal Beach', destination_id: puerto_santiago.id)
Hotel.create(name: 'Giada Florence', destination_id: santa_ursula.id)
Hotel.create(name: 'Valle Mar', destination_id: caribbean.id)
Hotel.create(name: 'Vilas Dinis - Adults Only', destination_id: bahamas.id)
Hotel.create(name: 'Villa Medici', destination_id: cayman_islands.id)
Hotel.create(name: 'Aquasol', destination_id: bermuda.id)
Hotel.create(name: 'American Hotel', destination_id: barbados.id)
Hotel.create(name: 'Side Star Park', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Primasud', destination_id: cuba.id)
Hotel.create(name: 'Londra', destination_id: jamaica.id)
Hotel.create(name: 'Barcelo Teguise Beach - Adults Only', destination_id: grenada.id)
Hotel.create(name: 'Hesperia Bristol Playa', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Late Apartments', destination_id: st_lucia.id)
Hotel.create(name: 'H10 Costa Adeje Palace', destination_id: maldives.id)
Hotel.create(name: 'Villa Padierna Palace Hotel', destination_id: male.id)
Hotel.create(name: 'Puerto Marina', destination_id: mauritius.id)
Hotel.create(name: 'Regency Torviscas Apartments Suites', destination_id: canaries.id)
Hotel.create(name: 'Melia Tamarindos', destination_id: fuerteventura.id)
Hotel.create(name: 'Clube Praia da Rocha', destination_id: antigua.id)
Hotel.create(name: 'Clube Porto Mos', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Sotavento', destination_id: corralejo.id)
Hotel.create(name: 'A10 Sol de Alcudia Apartments', destination_id: costa_calma.id)
Hotel.create(name: 'Parque Cattleya', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Playamar', destination_id: gran_canaria.id)
Hotel.create(name: 'Globales Playa Santa Ponsa', destination_id: arguineguin.id)
Hotel.create(name: 'Bahia Playa', destination_id: las_palmas.id)
Hotel.create(name: 'Marina Suites', destination_id: maspalomas.id)
Hotel.create(name: 'Varandas de Albufeira', destination_id: meloneras.id)
Hotel.create(name: 'Club Riu Gran Canaria', destination_id: playa_del_ingles.id)
Hotel.create(name: 'H10 Timanfaya Palace - Adults Only', destination_id: puerto_rico.id)
Hotel.create(name: 'Hotel Boreal', destination_id: san_agustin.id)
Hotel.create(name: 'Hd Parque Cristobal Tenerife', destination_id: sonnenland.id)
Hotel.create(name: 'Monaco Hotel', destination_id: lanzarote.id)
Hotel.create(name: 'Flamingo Cancun Resort & Plaza', destination_id: costa_calero.id)
Hotel.create(name: 'Relais Acropolis', destination_id: costa_teguise.id)
Hotel.create(name: 'Louvre', destination_id: matagorda.id)
Hotel.create(name: 'Hotel Flamboyan Caribe', destination_id: playa_blanca.id)
Hotel.create(name: 'Castillo San Jorge, Antigua', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Pestana Casino Park', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Ole Tropical', destination_id: tenerife.id)
Hotel.create(name: 'OH Marbella Inn', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Adriana Beach Club', destination_id: costa_adeje.id)
Hotel.create(name: 'Plaza Cavana', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Mercure Angioino Centro', destination_id: el_medano.id)
Hotel.create(name: 'Tropical Sol', destination_id: golf_del_sur.id)
Hotel.create(name: 'Geranios Suites & Spa', destination_id: las_caletillas.id)
Hotel.create(name: 'Roc Costa Park', destination_id: los_cristianos.id)
Hotel.create(name: 'IFA Beach Hotel - Adults Only', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Allegro Isora', destination_id: playa_paraiso.id)
Hotel.create(name: 'Janelas do Mar', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Cordial Green Golf', destination_id: puerto_santiago.id)
Hotel.create(name: 'Hotel Marco Polo - Adult Only', destination_id: santa_ursula.id)
Hotel.create(name: 'Doramar', destination_id: caribbean.id)
Hotel.create(name: 'Sabina', destination_id: bahamas.id)
Hotel.create(name: 'The Kocer Beach Hotel', destination_id: cayman_islands.id)
Hotel.create(name: 'Los Cardones', destination_id: bermuda.id)
Hotel.create(name: 'Best Benalmadena', destination_id: barbados.id)
Hotel.create(name: 'Maspalomas Oasis Club', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Barut Hotels Arum', destination_id: cuba.id)
Hotel.create(name: 'Duva', destination_id: jamaica.id)
Hotel.create(name: 'Capri', destination_id: grenada.id)
Hotel.create(name: 'Blue Bay Getaway Villas Doradas', destination_id: trinidad_and_tobago.id)
Hotel.create(name: '4Dreams Hotel Chimisay', destination_id: st_lucia.id)
Hotel.create(name: 'Correra 241', destination_id: maldives.id)
Hotel.create(name: 'Dorado Suites Hotel', destination_id: male.id)
Hotel.create(name: 'Palm Wings Ephesus Hotels And Resorts', destination_id: mauritius.id)
Hotel.create(name: 'Guinate Club', destination_id: canaries.id)
Hotel.create(name: 'Dom Pedro Baia Club', destination_id: fuerteventura.id)
Hotel.create(name: 'Palm Garden', destination_id: antigua.id)
Hotel.create(name: 'Playa Sur Tenerife', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Hotel Quinta Do Lago', destination_id: corralejo.id)
Hotel.create(name: 'Hotel Blue Sea Don Jaime', destination_id: costa_calma.id)
Hotel.create(name: 'Lagosmar', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Aloe', destination_id: gran_canaria.id)
Hotel.create(name: 'Hotel RF Astoria - Adults Only', destination_id: arguineguin.id)
Hotel.create(name: 'Topazio', destination_id: las_palmas.id)
Hotel.create(name: 'Metropole', destination_id: maspalomas.id)
Hotel.create(name: 'Casablanca - Adults Only', destination_id: meloneras.id)
Hotel.create(name: 'Rocamar', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Escorial', destination_id: puerto_rico.id)
Hotel.create(name: 'Sunset Beach Club', destination_id: san_agustin.id)
Hotel.create(name: 'Iris', destination_id: sonnenland.id)
Hotel.create(name: 'Idas Hotel', destination_id: lanzarote.id)
Hotel.create(name: 'Montechoro', destination_id: costa_calero.id)
Hotel.create(name: 'Jardins da Rocha', destination_id: costa_teguise.id)
Hotel.create(name: 'Dom Pedro Lagos', destination_id: matagorda.id)
Hotel.create(name: 'Blue Sky', destination_id: playa_blanca.id)
Hotel.create(name: 'Hotel Jandia Golf', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Club Hotel Tropicana', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Alfamar Beach & Sport Resort', destination_id: tenerife.id)
Hotel.create(name: 'El Puntazo', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Demircioglu Apart', destination_id: costa_adeje.id)
Hotel.create(name: 'Bernini Palace', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Menorca Patricia', destination_id: el_medano.id)
Hotel.create(name: 'Turbo Club', destination_id: golf_del_sur.id)
Hotel.create(name: 'Blue Sea Arenal Tower - Adult Only', destination_id: las_caletillas.id)
Hotel.create(name: 'Park Plaza', destination_id: los_cristianos.id)
Hotel.create(name: 'Le Meridien St. Julians', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Clube Alvorferias', destination_id: playa_paraiso.id)
Hotel.create(name: 'Los Arcos Montemar', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Sabina Playa', destination_id: puerto_santiago.id)
Hotel.create(name: 'Tropicana Studios', destination_id: santa_ursula.id)
Hotel.create(name: 'Mansion de Nazaret', destination_id: caribbean.id)
Hotel.create(name: 'Occidental Jandia Playa', destination_id: bahamas.id)
Hotel.create(name: 'Sol House Costa del Sol', destination_id: cayman_islands.id)
Hotel.create(name: 'Algarve Mor', destination_id: bermuda.id)
Hotel.create(name: 'Annabels', destination_id: barbados.id)
Hotel.create(name: 'Barcarola', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Vulcano', destination_id: cuba.id)
Hotel.create(name: 'Casa del Sol', destination_id: jamaica.id)
Hotel.create(name: 'Prainha Clube', destination_id: grenada.id)
Hotel.create(name: 'Fergus Bermudas', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Topaz', destination_id: st_lucia.id)
Hotel.create(name: 'Holiday Palace', destination_id: maldives.id)
Hotel.create(name: 'Vistamar Aparthotel', destination_id: male.id)
Hotel.create(name: 'Servatur Barbados', destination_id: mauritius.id)
Hotel.create(name: 'Europa', destination_id: canaries.id)
Hotel.create(name: 'Royal Savoy', destination_id: fuerteventura.id)
Hotel.create(name: 'Hesperia Playa Dorada', destination_id: antigua.id)
Hotel.create(name: 'Bay Gardens Inn', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Bungalows Coloradamar', destination_id: corralejo.id)
Hotel.create(name: 'Villas del Sol', destination_id: costa_calma.id)
Hotel.create(name: 'Harmony Suites', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Maris Beach', destination_id: gran_canaria.id)
Hotel.create(name: 'Puerto Plata', destination_id: arguineguin.id)
Hotel.create(name: 'Costa Canaria - Adults Only', destination_id: las_palmas.id)
Hotel.create(name: 'Las Palmeras', destination_id: maspalomas.id)
Hotel.create(name: 'Villa Flamenca', destination_id: meloneras.id)
Hotel.create(name: 'All Sun Esquinzo Beach Hotel', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Corfu Chandris', destination_id: puerto_rico.id)
Hotel.create(name: 'Grand Blue Sky International', destination_id: san_agustin.id)
Hotel.create(name: 'Caledonia Park', destination_id: sonnenland.id)
Hotel.create(name: 'Costa Sal', destination_id: lanzarote.id)
Hotel.create(name: 'Continental', destination_id: costa_calero.id)
Hotel.create(name: 'Seler', destination_id: costa_teguise.id)
Hotel.create(name: "L'Ambiance", destination_id: matagorda.id)
Hotel.create(name: 'Las Tejas', destination_id: playa_blanca.id)
Hotel.create(name: 'Rosalia', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Neapolis', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'HSM President', destination_id: tenerife.id)
Hotel.create(name: 'Vendome', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'Villas Salinas de Matagorda', destination_id: costa_adeje.id)
Hotel.create(name: 'Fergus Style Pollensa Park', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Cantur City Hotel', destination_id: el_medano.id)
Hotel.create(name: 'Riu Costa Lago', destination_id: golf_del_sur.id)
Hotel.create(name: 'Elegance', destination_id: las_caletillas.id)
Hotel.create(name: 'Royal Panacea Hotel', destination_id: los_cristianos.id)
Hotel.create(name: 'Juliani', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Grupotel Maritimo', destination_id: playa_paraiso.id)
Hotel.create(name: 'Sol Alcudia Center', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Pateo Village', destination_id: puerto_santiago.id)
Hotel.create(name: 'Hoposa Montelin', destination_id: santa_ursula.id)
Hotel.create(name: 'Panorama - Adults Only', destination_id: caribbean.id)
Hotel.create(name: 'Balaia Mar', destination_id: bahamas.id)
Hotel.create(name: 'La Barracuda', destination_id: cayman_islands.id)
Hotel.create(name: 'Isabel', destination_id: bermuda.id)
Hotel.create(name: 'Golden Odyssey', destination_id: barbados.id)
Hotel.create(name: 'Club Turkuaz', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Zafiro Bahia', destination_id: cuba.id)
Hotel.create(name: "Illa d'Or", destination_id: jamaica.id)
Hotel.create(name: 'Carema Beach Menorca (ex Siesta Playa)', destination_id: grenada.id)
Hotel.create(name: 'Lima', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Mediterranean Hotel', destination_id: st_lucia.id)
Hotel.create(name: 'Riu Arecas', destination_id: maldives.id)
Hotel.create(name: 'Flor Da Laranja', destination_id: male.id)
Hotel.create(name: 'Campanario de Calahonda', destination_id: mauritius.id)
Hotel.create(name: 'Pasa Beach Hotel', destination_id: canaries.id)
Hotel.create(name: 'Calamijas', destination_id: fuerteventura.id)
Hotel.create(name: 'Akrotiri Beach', destination_id: antigua.id)
Hotel.create(name: 'Club Simo Aparthotel', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Magna Grecia', destination_id: corralejo.id)
Hotel.create(name: 'Delfin Casa Vida Apartments', destination_id: costa_calma.id)
Hotel.create(name: 'Rex Hotel', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Beatriz Playa & Spa', destination_id: gran_canaria.id)
Hotel.create(name: 'HL Club Playa Blanca', destination_id: arguineguin.id)
Hotel.create(name: 'Relaxia Los Girasoles (Bungalows)', destination_id: las_palmas.id)
Hotel.create(name: 'Ozadi Tavira Hotel', destination_id: maspalomas.id)
Hotel.create(name: 'Estalagem Quinta da Casa Branca', destination_id: meloneras.id)
Hotel.create(name: 'Aquamarina Beach Resort Hotel', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Zurbaran', destination_id: puerto_rico.id)
Hotel.create(name: 'Julian Marmaris', destination_id: san_agustin.id)
Hotel.create(name: 'Arena Center', destination_id: sonnenland.id)
Hotel.create(name: 'Alp Hotel', destination_id: lanzarote.id)
Hotel.create(name: 'Moon Palace', destination_id: costa_calero.id)
Hotel.create(name: 'Apartamentos Royal Life', destination_id: costa_teguise.id)
Hotel.create(name: 'Vistasur', destination_id: matagorda.id)
Hotel.create(name: 'Aquis Palace Mon Repos - Adult Only', destination_id: playa_blanca.id)
Hotel.create(name: 'Alondra Suites', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Vila Gale Praia - Adults Only', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Atlantis Apart', destination_id: tenerife.id)
Hotel.create(name: 'Interpass Vauhotel Apartamentos', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'AC Ciutat de Palma', destination_id: costa_adeje.id)
Hotel.create(name: 'Bluebay Banus', destination_id: costa_del_silencio.id)
Hotel.create(name: 'Sotavento', destination_id: el_medano.id)
Hotel.create(name: 'Gran Bahia Principe Ambar - Adults Only', destination_id: golf_del_sur.id)
Hotel.create(name: 'Pyr Fuengirola', destination_id: las_caletillas.id)
Hotel.create(name: 'Riu Playa Cala Millor', destination_id: los_cristianos.id)
Hotel.create(name: 'Cheerfulway California Hotel', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Grand Cettia', destination_id: playa_paraiso.id)
Hotel.create(name: 'Hotel Globales Pionero/Santa Ponsa Park', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Sur', destination_id: puerto_santiago.id)
Hotel.create(name: 'Kraft', destination_id: santa_ursula.id)
Hotel.create(name: 'The Westin Dragonara Resort', destination_id: caribbean.id)
Hotel.create(name: 'Bahia de Alcudia', destination_id: bahamas.id)
Hotel.create(name: 'Monteparaiso', destination_id: cayman_islands.id)
Hotel.create(name: 'Pine Cliffs Hotel, a Luxury Collection Resort', destination_id: bermuda.id)
Hotel.create(name: 'Tabaiba / Maspalomas Princess', destination_id: barbados.id)
Hotel.create(name: 'Sahara Playa', destination_id: antigua_and_barbuda.id)
Hotel.create(name: "Playas Ca's Saboners", destination_id: cuba.id)
Hotel.create(name: 'Isla Mallorca', destination_id: jamaica.id)
Hotel.create(name: 'Senses Palmanova - Adults Only', destination_id: grenada.id)
Hotel.create(name: 'Hovima Atlantis', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Le Meridien Penina Golf & Resort', destination_id: st_lucia.id)
Hotel.create(name: 'Grand Onder Hotel', destination_id: maldives.id)
Hotel.create(name: 'Simbad', destination_id: male.id)
Hotel.create(name: 'St. Lucian by Rex Resorts', destination_id: mauritius.id)
Hotel.create(name: 'Los Nardos', destination_id: canaries.id)
Hotel.create(name: 'Ibiscus Hotel', destination_id: fuerteventura.id)
Hotel.create(name: 'Nuovo Rebecchino', destination_id: antigua.id)
Hotel.create(name: 'Faro', destination_id: caleta_de_fuste.id)
Hotel.create(name: 'Iberostar Marbella Coral Beach - Adult Only', destination_id: corralejo.id)
Hotel.create(name: 'Club del Sol', destination_id: costa_calma.id)
Hotel.create(name: 'Tortuga Bay', destination_id: playa_de_jandia.id)
Hotel.create(name: 'Apartments THe Las Gaviotas', destination_id: gran_canaria.id)
Hotel.create(name: 'HG Cala Llonga', destination_id: arguineguin.id)
Hotel.create(name: 'La Reserva de Marbella', destination_id: las_palmas.id)
Hotel.create(name: 'Playa del Ingles', destination_id: maspalomas.id)
Hotel.create(name: 'Las Tartanas', destination_id: meloneras.id)
Hotel.create(name: 'Pestana Palms', destination_id: playa_del_ingles.id)
Hotel.create(name: 'Morana', destination_id: puerto_rico.id)
Hotel.create(name: 'Iberostar Playa Gaviotas', destination_id: san_agustin.id)
Hotel.create(name: 'IFA Interclub Atlantic', destination_id: sonnenland.id)
Hotel.create(name: 'Excelsior', destination_id: lanzarote.id)
Hotel.create(name: 'Bay Gardens Hotel', destination_id: costa_calero.id)
Hotel.create(name: 'Buensol', destination_id: costa_teguise.id)
Hotel.create(name: 'Meridmar Apart', destination_id: matagorda.id)
Hotel.create(name: 'Globales Tamaimo Tropical', destination_id: playa_blanca.id)
Hotel.create(name: 'Saint Gothard', destination_id: puerto_del_carmen.id)
Hotel.create(name: 'Blancala', destination_id: playa_de_los_pocillos.id)
Hotel.create(name: 'Sheraton La Caleta Resort and Spa', destination_id: tenerife.id)
Hotel.create(name: 'Hotel Jose Cruz', destination_id: playa_de_las_americas.id)
Hotel.create(name: 'El Tope', destination_id: costa_adeje.id)
Hotel.create(name: 'Brisa - Adults Only', destination_id: costa_del_silencio.id)
Hotel.create(name: 'La Cala Resort', destination_id: el_medano.id)
Hotel.create(name: 'Estalagem do Cerro', destination_id: golf_del_sur.id)
Hotel.create(name: 'El Rodat', destination_id: las_caletillas.id)
Hotel.create(name: 'Altamira', destination_id: los_cristianos.id)
Hotel.create(name: 'Excellence Playa Mujeres - Adults Only', destination_id: playa_de_la_arena.id)
Hotel.create(name: 'Vigilia Park', destination_id: playa_paraiso.id)
Hotel.create(name: 'Vistamar', destination_id: puerto_de_la_cruz.id)
Hotel.create(name: 'Jandia Princess', destination_id: puerto_santiago.id)
Hotel.create(name: 'Grand Hotel Minerva', destination_id: santa_ursula.id)
Hotel.create(name: 'Arena', destination_id: caribbean.id)
Hotel.create(name: 'Solemar', destination_id: bahamas.id)
Hotel.create(name: 'Dom Pedro Marina', destination_id: cayman_islands.id)
Hotel.create(name: 'Holiday Inn Resort Nice-Port St. Laurent', destination_id: bermuda.id)
Hotel.create(name: 'Hotel Labranda Marieta', destination_id: barbados.id)
Hotel.create(name: 'Servatur Hotel Puerto Azul', destination_id: antigua_and_barbuda.id)
Hotel.create(name: 'Sol Don Pedro', destination_id: cuba.id)
Hotel.create(name: 'Inagua', destination_id: jamaica.id)
Hotel.create(name: 'Bellevue Lagomonte', destination_id: grenada.id)
Hotel.create(name: 'R2 Rio Calma Hotel', destination_id: trinidad_and_tobago.id)
Hotel.create(name: 'Atlantic Garden Beach Mate', destination_id: st_lucia.id)
